### ISSUE TITLE
Problem with STBValidatingInFiler on socket

### ISSUE THREAD

**Issue by pjavier29** [dolphinsmalltalk/Dolphin#1012]
I have an application that uses socket connections, similar to the Chat example included in Dolphin. The problem is that the 'peekForSignatureIn: aReadStream' method in dolphin 7.1.9 called the message 'next:' of the aReadStream. If the ReadStream is a SocketReadStream then it derives on the blocking method 'receiveSome: aByteObject count: lengthInteger startingAt: startInteger' until data arrives.
In Dolphin 7.1.14 the message 'nextAvailable:' is invoked instead of 'next:' which does other things but does not block waiting for data to arrive, which causes socket communication to fail. In fact the example of the Chat class does not work anymore.
I don't know if it's Dolphin's problem or I'm bad. Please have any suggestions.
Thank you very much.
Sorry for my bad English.
Regards

**Comment by blairmcg** [comment]
`Stream>>nextAvailable:` needs to be copied down to SocketReadStream, then it should work.

**Comment by pjavier29** [comment]
I tried what you suggested and it worked fine.
Thank you very much.
Regards
