### ISSUE TITLE
Boot failed for BootDPRO.cmd

### ISSUE THREAD

**Issue by dram** [dolphinsmalltalk/Dolphin#1065]
**Describe the bug**

When using DolphinVM v7.1.16 to create DPRO image from latest master (95f6664), following error occurred:

```
Dolphin Smalltalk Boot
Copyright (c) Object Arts Ltd, 1997-2018.
Boot started at 2020-12-07T08:17:44.607904434+08:00
Loading boot script...
Reloading BCL constants pools...
Updating ClassBuilder...
Reloading BCL class definitions...
Reloading BCL classes...
Error: CompiledCode>>setByteCodes: at line 2: invalid primitive call type 'mutable'
Error: CompiledCode>>sourceDescriptor: at line 4: invalid primitive call type 'mutable'
Boot failed, Code=-1073741819
```

**To Reproduce**
1. Checkout Dolphin git repo https://github.com/dolphinsmalltalk/Dolphin
2. Download DolphinVM from https://github.com/dolphinsmalltalk/Dolphin/releases
3. run BootDPRO.cmd

**Expected behavior**
BootDPRO.cmd should run successfully, and a DRPO image should be created.

**Please complete the following information:**
 - OS: Windows 10

**Comment by blairmcg** [comment]
I'd forgotten to press the Github release button on the 7.1.17 VM. 
v7.1.18 is released now. You'll need to fetch and move yourself to the head of master, and then run the fetchvm script. 
Alternatively, build the VM, which should always work if the CI build is working.
