### ISSUE TITLE
Error trying to create an image using FetchVM.ps1

### ISSUE THREAD

**Issue by rejurime** [dolphinsmalltalk/Dolphin#1070]
**Describe the bug**
Error trying to create an image using FetchVM.ps1

**To Reproduce**
1. Right click on the FetchVM.ps1 file and choose Run with PowerShell
2. Throw the following error `Unable to fetch DolphinVM.zip v7.1.4`

**Please complete the following information):**
 - OS: Windows 10

**Additional context**
If I change to another version in the script (FetchVM.ps1) works fine for example 7.1.14, the problem is with the 7.1.4 version.

**Comment by blairmcg** [comment]
Is there any particular reason you need to use 7.1.4? It is a pretty old version; 25th April 2019, i.e. more than 18 months old.  Unless you particularly want to build the Smalltalk image as at that tag, that version of the VM is not going to work with the more recent Smalltalk code anyway. If you do really need to use 7.1.4 (or any version from there up to 7.1.8), then you will have to build it with VisualStudio.

Perhaps you are just running Fetchvm.ps1 directly, in which case you won't be benefiting from the `git describe` command in its FetchVM.cmd wrapper that ensures you get the version associated with the latest tag.
