### ISSUE TITLE
ListViews failing to paint correctly when refreshed for a smaller set of items

### ISSUE THREAD

**Issue by blairmcg** [dolphinsmalltalk/Dolphin#1071]
PR##1068 has caused a regression in ListView behaviour which can be seen when moving from a long to a shorter list, e.g. in class or package browsers. This is not to do with the changes in the calculation, but rather due to the calculation now being performed when #onPositionChanged: is sent for a SWP_FRAMECHANGED notification. The control sends such a position changing notification (i.e. a WM_WINDOWPOSCHANGING message) when it is sent an LVM_SETITMECOUNT message, as this is how the number of items to display in a ListView in virtual mode is communicated to the control. It seems that responding to the position changing event in this case with operations that affect the view geometry causes the control's internal state to become corrupted. Specifically the scroll origin gets set to an incorrect value such that the displayed rows are offset outside the painted area.

The limitations as to what is allowed in a WM_WINDOWPOSCHANGING handler are not documented for SysListView, but it is not that unusual for such limitations to be present.

If the ListView>>onPositionChanging: handler is modified so that the auto-column sizing is only performed on actual resizes, then the bug does not occur. However, this has other consequences (such as not responding to real frame size changes, e.g. from changing edge styles), which causes some of the new tests to fail. 

Historically the ListView integration did not correctly adjust column widths dynamically when edge styles were changed, and it would not be unreasonable to revert to that, although obviously the tests will need some adaptation.

**Repro Steps**

1. Open a class browser
2. Select Object
3. Scroll down the method list to the bottom
4. Select Animal - note that no methods are visible
5. Select Object again - no methods are visible, until one scrolls down the list

At step 5 it is instructive to use the visual object finder to open an inspector on the method list view, and then evaluate a `self lvmGetOrigin` to see the scroll origin, which will have a fairly large negative 'y' component when it should be zero.

![image](https://user-images.githubusercontent.com/15128107/102114212-dacb2c80-3e31-11eb-9f1f-55a630f9fcc6.png)

**Comment by daniels220** [comment]
Ouch, good catch. It does look like messing with column widths when scrollbars are changing is just not allowed, so we pretty much have to change to `isResize` as you did. It's easy enough to tweak the tests to work in that case, by resizing the view up and back down by 1px after changing the frame style. This does point out that adding a column doesn't trigger an auto-resize—it does trigger a WM_WINDOWPOSCHANGED with SWP_FRAMECHANGED, but since we can't respond to that, maybe add an explicit `self autoResizeColumns` in...well, a few places on ListViewColumn.

**Comment by blairmcg** [comment]
Fixed by #1075
