### ISSUE TITLE
Unable to open or edit DatePresenter.Month view

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#109]
ViewComposer openOn: (ResourceIdentifier class: DatePresenter selector: #resource_Month_view).

2:56:57 PM, Thursday, March 03, 2016: 'Unspecified error (16r4005: Unspecified error)'
IDolphinAxHost(COMInterface)>>hresultError:
IDolphinAxHost(ExternalStructure)>>invalidCall
IDolphinAxHost>>CreateControlLicEx:hWnd:pStream:ppUnk:piAdvise:bstrLic:
IDolphinAxHost>>createControlLicEx:hWnd:pStream:piAdvise:bstrLic:
MonthView(AXControlSite)>>safeCreateControlFromStream:
MonthView(AXControlSite)>>controlBinaryStoreBytes:
MessageSend(MessageSendAbstract)>>value
[] in MessageSequenceAbstract>>value
OrderedCollection>>do:
MessageSequence>>messagesDo:
MessageSequence(MessageSequenceAbstract)>>value
MonthView(View)>>state:
MonthView(STBViewProxy)>>restoreView
MonthView(STBViewProxy)>>restoreTopView
[] in MonthView(STBViewProxy)>>stbFixup:at:
[] in STBInFiler>>evaluateDeferredActions
OrderedCollection>>do:
STLInFiler(STBInFiler)>>evaluateDeferredActions
STLInFiler(STBInFiler)>>next
[] in DesktopView(View)>>loadViewResource:forEdit:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
DesktopView(View)>>loadViewResource:forEdit:
[] in SmalltalkSystem>>loadViewResource:inContext:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
RefactoringSmalltalkSystem(SmalltalkSystem)>>loadViewResource:inContext:
ViewComposer>>basicPasteResource:context:
ViewComposer>>pasteResource:context:position:
ViewComposer>>openOn:
ViewComposer class>>openOn:
DatePresenter class>>{unbound}doIt

**Comment by blairmcg** [comment]
The activex control this used is obsolete so I've removed the package from the product description.
