### ISSUE TITLE
Optimization of Collection >> #distinct

### ISSUE THREAD

**Issue by Sergiomdf** [dolphinsmalltalk/Dolphin#1093]
I suggest a little change to optimize Collection >> #distinct.

In a workspace:
>largeCollection := (1 to: 10000000) asArray.
Time millisecondsToRun: [largeCollection distinct]. "7467 ms"
Time millisecondsToRun: [largeCollection , largeCollection distinct]. "7831 ms"

Current implementation:
>seen := Set new.

Suggested change:
>seen := Set new: self size.

New times:
4838 ms and 5242 ms respectively, performing 35 and 33% better.
28 and 35% better when using an OrderedCollection.

**Comment by blairmcg** [comment]
It is a good idea, but at the most abstract `Collection` level, we cannot assume that `size` is state, as it may need to be calculated. The implementation in `Collection` itself is to enumerate and count the elements. Hence `size` is generally not used in `Collection` methods. Looking at the `Collection` methods that do self send `size`, there are very few:

- `asArray`
- `asByteArray`
- `isEmpty`
- `noDifference:`

Of these, only `isEmpty` should really be using it. The conversions to `Array`/`ByteArray` should be writing into streams (which may actually be faster for some cases as it avoids the full blocks, and probably not that different overall). `#noDifference:` should not be using it either.

You've also only tested one extreme cases - a very large sequence with no duplicates, which is one of the cases where the gain in pre-sizing the Set will be largest. 

Your 2nd expression is really just testing the same thing as you are missing parenthesis around the concatenation, assuming you want to measure how long it takes to de-dup the array doubled up (although it would be better to take the concatenation time out of the measure). 
```
double := largeCollection, largeCollection.
[double distinct] timeToRun "Display-it"
```

**Comment by blairmcg** [comment]
I've just remembered that there is `approxSize` for the purpose of getting the best available size quickly (from state if available, or a guess, perhaps wildly inaccurate, if not).

**Comment by Sergiomdf** [comment]
Sorry, my bad. In fact I am using #copySize.
