### ISSUE TITLE
No release/7.1 branch

### ISSUE THREAD

**Issue by dram** [dolphinsmalltalk/Dolphin#1094]
It seems that `release/7.1` branch is missing, according to this page: https://github.com/dolphinsmalltalk/Dolphin/branches

**Comment by blairmcg** [comment]
There was, but when I PR' d it to master to establish a baseline I forgot to uncheck the option to delete the branch: https://github.com/dolphinsmalltalk/Dolphin/pull/1091
Sorry about that. Now restored.
