### ISSUE TITLE
Image Stripping fails with MNU #lookup:

### ISSUE THREAD

**Issue by rko281** [dolphinsmalltalk/Dolphin#1095]
Image Stripping is failing in D7.1 with `UndefinedObject does not understand #lookup:` in `ExternalStructure class>>canUnderstand:`. This checks the class's template but the class's ability to instantiate this has already been removed in `BasicImageStripper>>compileExternalStructuresNow:`.

To reproduce try deploying the XmlPad app in D7.1.

Adding `#canUnderstand:`to the array of removed selectors in `BasicImageStripper>>compileExternalStructuresNow:` fixes this:

```smalltalk
        self removeSelectors: #(#getFieldNames #canUnderstand:) of: ExternalStructure class
```

**Comment by blairmcg** [comment]
Fixed by #1096 in 1317c44
