### ISSUE TITLE
Add .gitattributes to correctly handle eol conversions

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/Dolphin#11]
Actually, downloading the project from GitHub using the "download as zip" link results in smalltalk source code corruption in image builds.
The same happens when the repository is cloned from a computer with the core.autocrlf (git config option) set to false.

The problem is originated in the automatic eol conversion done by git.

To solve both problems a .gitattributes file is needed as is explained [here](https://help.github.com/articles/dealing-with-line-endings/)

**Comment by fxgallego** [comment]
Andy, I'm working on this with interruptions but taking care of handling both cases because is a headache to merge when line endings are wrong. I'm not sure if you can assign this to me directly.

**Comment by fxgallego** [comment]
I have two different approaches for the *.gitattributes* file. Both solves cloning and download from zip.

**Solution 1**
```text
* text 	eol=crlf
*.img 	binary
*.img7	binary
*.exe 	binary
*.dll 	binary
*.chm 	binary
*.hlp 	binary
*.vu 	binary
*.stb 	binary
*.ico 	binary
*.gif 	binary
*.gz  	binary
*.zip 	binary
*.jpg 	binary
*.png 	binary
*.olb 	binary

*.sml 	text
*.pax 	text
*.st 	text
*.pac 	text
*.cls 	text
```

**Solution 2**
```text
*.img 	binary
*.img7	binary
*.exe 	binary
*.dll 	binary
*.chm 	binary
*.hlp 	binary
*.vu 	binary
*.stb 	binary
*.ico 	binary
*.gif 	binary
*.gz  	binary
*.zip 	binary
*.jpg 	binary
*.png 	binary
*.olb 	binary

*.sml 	eol=crlf
*.pax 	eol=crlf
*.st 	eol=crlf
*.pac 	eol=crlf
*.cls 	eol=crlf
*.cmd	eol=crlf
*.md	eol=crlf
*.txt	eol=crlf
LICENSE eol=crlf
*.gitignore eol=crlf
*.gitattributes eol=crlf
```

Solution 1: Marks all files as "text" using crlf. It does the job but I think is as effective as dangerous. If you don't mark binary files maybe you can end with a corrupted binary.

Solution 2: Only the annotated files area changed to eol=crlf. If you add a new file type you must remember to add an annotation.

For now, I do prefer Solution 2. It's more conservative.
You only need to add a ".gitattributes" file at the root folder with one of the solutions. I think there is no reason to create a pull request for this.

**Comment by objectarts** [comment]
Hi Sebastian,
Isn't the real problem with corrupted source the fact that Dolphin treats _some_ text files (*.sml, *.chg) as if they were not actually pure text. I think the issue is only relevant for these files because the image keeps indices into these files to mark the location of source elements it needs to locate. Hence, switching between LF and CRLF endings messes up the count and appears to corrupt the source.

So, can we not use * text=auto for most test files (which will allow them to be read properly on Unix/Mac) but just specify *.chg=crlf and *.sml=crlf separately? Are you in a position to test if this will work?

BTW, regarding assignment of issues to people, I shall soon move the repos to a DolphinSmalltalk GitHub organization (it's currently under a user) and then we can specify people who want to work on different topics.

**Comment by fxgallego** [comment]
Andy, yes, I'm aware that the problem is with the positions on the sml.
Now, that you mention about the * text=auto, I realize that this .gitattributes settings overrides the own user config so I think it's possible and preferable. I think the only problem with this setting will be that files not annotated as crlf will be downloaded (button) from github with LF. That's something to take into account but not a problem for development. I'll test this today later and let you know.

**Comment by fxgallego** [comment]
I was confused with this comment in the git help:
>Set the default behavior, in case people don't have core.autocrlf set.
> '* text=auto
But I do have core.autocrlf set so...

Anyway it works like a charm.

* text=auto
*.sml 	eol=crlf
*.chg 	eol=crlf

When you download the zip from github you get all files with LF with exception of the sml. I think (for now) this is enough for users that only want to build the image. Maybe you want in this list (crlf) the license  and the cmd files. You are the boss :)

With that setting I had not eol conversion problems anymore when cloning with core.autocrlf=false set.

**Comment by bernhardkohlhaas** [comment]
After switching my local configuration back to autocrlf=false, I tried this with the currently latest commit ( https://github.com/fxgallego/Dolphin/commit/23874df64365269be82ec66dc80b8cfc88ee4bd0 ) and it appears to work fine with the git CLI. You get CRLF in the sml and chg files as well as the cls and pax files in the Core/ subdirectory hieararchy, even for the license and cmd files.

**Comment by objectarts** [comment]
Have applied this fix to latest [master](https://github.com/dolphinsmalltalk/Dolphin/commit/097b5eb45cd73adca4418c961ddbf912a6ab317c). Thanks for all the help.
