### ISSUE TITLE
GPF opening MaskedEdit

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#110]
ViewComposer openOn: (ResourceIdentifier class: TextPresenter selector: #resource_Masked_edit).

Unhandled exception - a GPFault('Invalid access to memory location. Reading 0x0, IP 0x1001B3B8 (M:\Documents\Dolphin\DolphinVM7.DLL)')

ProcessorScheduler>>gpFault:
[] in ProcessorScheduler>>vmi:list:no:with:
BlockClosure>>ifCurtailed:
ProcessorScheduler>>vmi:list:no:with:
IMSMask(ExternalStructure)>>invalidCall
IMSMask>>get_Text:
IMSMask>>text
MaskedEdit>>plainText
MaskedEdit(View)>>text
MaskedEdit(View)>>state
MaskedEdit(AXControlSite)>>state
STBViewProxy>>setView:
STBViewProxy class>>forView:
MaskedEdit(View)>>filerProxy
MaskedEdit(View)>>stbSaveOn:
STLOutFiler(STBOutFiler)>>basicNextPut:
STLOutFiler(STBOutFiler)>>writeInstanceVariables:
STLOutFiler(STBOutFiler)>>writeObject:as:withPrefix:
STLOutFiler(STBOutFiler)>>saveObject:
Array(Object)>>stbSaveOn:

**Comment by blairmcg** [comment]
I think we should just remove this package, especially as it actually crashes Dolphin. The MaskedEdit view relies on an old Active-X control that is no longer routinely distributed.

**Comment by blairmcg** [comment]
Now removed so this can be closed
