### ISSUE TITLE
Why was DevelopmentSessionManager>>git: removed?

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#1101]
See 100c5ae90781bd885d38331f6cb566ccdf362992 on 7-Feb-2021.

**Comment by blairmcg** [comment]
Is there an issue, or is this just a question? If the latter, we should try the Discussion for this now.

I can't remember what prompted me to remove it (the change was made many months ago), but I was probably struggling to get the image to boot and removed it to reduce dependencies. However, some general git utility that is only used to import boot version information doesn't belong in the runtime session manager for the development system. It shouldn't be a dumping ground for general utilities that are unrelated to its purpose. In this case it was introduced for a boot-time only operation, and would probably have been put in the boot session manager if it were not for the absence of the external process package in the boot image. The functionality was moved to the place where it is used.

**Comment by jgfoster** [comment]
It looks like it disappeared just ten days ago (based on the SHA I found in a binary search looking for an explanation). I was using it to generate a version number as part of my deployment process and I didn't find an obvious replacement so I duplicated the code. Is the new place publicly available?

**Comment by blairmcg** [comment]
That's just the commit date. Looks like it dates back to the end of June last year.
```
git log 100c5ae90781bd885d38331f6cb566ccdf362992 -1
commit 100c5ae90781bd885d38331f6cb566ccdf362992
Author: Blair McGlashan <blairmcg@outlook.com>
Date:   Sun Jun 28 16:43:09 2020 +0100

    File out base Development System packages in new format
```
It only exists in the boot script, so I would duplicate the code as you have done.
