### ISSUE TITLE
Core.True>>xor:  - misleading description (method comment)

### ISSUE THREAD

**Issue by FBek055** [dolphinsmalltalk/Dolphin#1105]
**Describe the bug**
Not really a bug but a misleading description of the _Core.True>>xor:_ method, probably due to an incomplete editing. The code itself is correct.

**To Reproduce:**
`True >> xor: operand`
`"Answer whether either the receiver or the boolean argument <operand> is true, but not both.
	Since the receiver is **_false_**, the answer is true only if the argument is false." `
`^operand not `

**Expected behavior:**
Replace **_false_** by **_true_** in the method description to read:
` "Answer whether either the receiver or the boolean argument <operand> is true, but not both. Since the receiver is **_true_**, the answer is true only if the argument is false."`
      
**Please complete the following information:**
 - OS: Windows 10

**Comment by blairmcg** [comment]
Fixed by  1cbd7a37cc64d44c85b6f0adbbca9791d0c97a8f
