### ISSUE TITLE
7.2.9 unable to install GitHub package issue with URLMonLibrary

### ISSUE THREAD

**Issue by sanjayminni** [dolphinsmalltalk/Dolphin#1111]
system does not install rko281/GitHub
after a full install Dolphin7Setup.exe
on trying to evaluate 
SourceManager default fileIn: (URLMonLibrary default urlDownloadToCacheFile: 'https://raw.githubusercontent.com/rko281/GitHub/master/install.st').
in workspace 
status bar shows error on URLMonLibrary

**Comment by blairmcg** [comment]
I should draw your attention to the comment at the top of the readme if you are using any 7.2 build:

**Please note: The master branch is now the development branch for version 7.2. This will add support for namespaces, but is currently in an interim and unstable state. It also changes the package and class file formats, and consequently code saved from 7.2 cannot be loaded directly into earlier versions of Dolphin. Please use the release/7.1 branch if you need a stable version. PRs for bug fixes, etc, will still be accepted against the release/7.1 branch for the foreseeable future.**

The comment is slightly out of date in that old format packages should save back out in the same format, although of course that will only work as long as dependencies on new stuff (or namespace classes) are not added.

`URLMonLibrary` is in the namespace OS.COM:

![image](https://user-images.githubusercontent.com/15128107/114907606-2824ce00-9e13-11eb-95d4-cfa777e99431.png)

Classes in certain namespaces (Core, Kernel, UI, OS, External and Tools) are imported into Smalltalk, and so remain globally visible to old code and scripts. OS.COM is not imported. In some other cases aliases for "old" class names are installed into the `Smalltalk` namespace.  `URLMonLibrary` is not one of those so far, but given the pre-existing use in a useful 3rd-party extension it perhaps should be. You could try loading the up the package using the alternative instructions given, but it may have other dependencies that don't work.
