### ISSUE TITLE
[Docs] Intent of paragraph in STONReader.cls

### ISSUE THREAD

**Issue by brickviking** [dolphinsmalltalk/Dolphin#1130]
I'm a little confused as to how the following paragraph from Core/Object Arts/Dolphin/System/STON/STON.Reader.cls:29:1490 is supposed to read. So far, I've managed to wrestle it into the following:

... There is potential danger in using a swapping `become:` for classes that use the normal STON object representation, but which create some sort of external reference while the object itself is being instantiated (e.g. a registry for sharing), _and which may internal references_. ...

Should I tweak it so it says: and which may _have_ internal references.
or, do I put:  and which may _not have_ internal references?

Cheers, brickviking

**Comment by blairmcg** [comment]
may have

**Comment by brickviking** [comment]
Thank you. I'm just working my way through all of the comments and strings and trying to find obvious stuff, I think I've got about 15% done so far. Do you want me to batch them up and push them all through at once, or send them through in smaller lumps of about 20-30 files?

**Comment by brickviking** [comment]
Core/Object Arts/Dolphin/Sockets/Socket.cls:121  says this:
```
	"Connect to the socket to a ServerSocket without blocking. 
```
Should this read
 + "Connect to the socket _on_ a ServerSocket without blocking." or
 + "Connect the socket to a ServerSocket without blocking."?

Cheers again.

**Comment by blairmcg** [comment]
The 2nd, but you've reminded me to delete this package.
