### ISSUE TITLE
Missing PublishedAspects in DevelopmentManager preferences.

### ISSUE THREAD

**Issue by brickviking** [dolphinsmalltalk/Dolphin#1145]
**Le bug**
When looking at User Preferences->Development System, there aren't any preferences shown for Dolphin-8.0.2-91, though the preferences appear for 7.1.20-10 and also 7.1.20-27 (latest at this date).

**Reproducing bugs**
Steps to reproduce the behaviour:
1. Start up Dolphin-8, go to 'User Preferences' in the System Folder.
2. Click on 'Development System'
3. Nothing appears in the property list for 8.0.2

**Not bugged behaviour**
Preferences should be visible for 8.0.2 as well. I suspect it might have something to do with #1133, but I don't know if the same fix would apply.

**Bug Screenshots**
I've included a screenshot for both versions - 8.0.2 to the left, 7.1.20 to the right, along with an Inspector opened on each RefactoringSmalltalkSystem. Sorry about the quality of the image, click on it to see a larger version.

![DevelopmentSystem-UserPrefs_7 1 20-10_8 0 2-91](https://user-images.githubusercontent.com/62885/126149535-e2278143-adaf-4d4c-a099-b9d7ab1f2834.png)

**Please complete the following information):**
 - OS: 32-bit Vista, 64-bit Fedora Linux, not a wine bug (thankfully)
 - Dolphin versions:
   - 7.1.20-10-g1f545adb2
   - 7.1.20-27-gaddbac065
   - 8.0.2-91-gb9b88949f

**Other information**
When looking at Instance variables in each Inspector, both versions have filled-out variables, however several of the variables in 8.0.2 are set to nil. On 7.1.20, the variables are set to other things aside from nil. Selecting other entries shows that they have preferences showing.

![DevelopmentSystem-InspectVariabless_7 1 20-10_8 0 2-91](https://user-images.githubusercontent.com/62885/126151474-286e72ce-4e63-4c51-8196-a66aaf48b797.png)

Trying to manually set the variables to anything in the Inspector doesn't reflect in the Settings, which is frustrating.

**Comment by blairmcg** [comment]
Fixed by 7471028d81e37bd96add8eef52eb091a5c042ed0
