### ISSUE TITLE
Support ARM processor

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#1171]
I have Windows running on an ARM processor (M1 Pro on a 14" MacBook Pro) and a Visual Studio build fails with `MSB3721: The command "ml.exe ..." exited with code 1.` I assume that this is because parts of Dolphin are written in assembly language. I understand that this will probably be a low priority, but at least this will provide a placeholder for an explanation that it doesn't work!

**Comment by jgfoster** [comment]
It turns out that Visual Studio 2022 (17.3.0 Preview 6.0) is able to build and run an x86 executable when running on ARM. the problem is that while it can find the C++ cross-compiler it is not able to find the x86 cross-assembler (see https://developercommunity.visualstudio.com/t/1730-Preview-60-unable-to-find-mlexe/10113911). When that path is added manually then it builds Dolphin fine.

**Comment by blairmcg** [comment]
The external issue was apparently fixed by Microsoft in VS2022 17.4. 
Native support for ARM is (realistically) not going to happen.
