### ISSUE TITLE
Unexpected delay forking a process

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#1189]
```code
5 timesRepeat: [
    | t |
    t := Time millisecondsToRun: [
        [] forkAt: Processor userBackgroundPriority.
    ].
    Transcript show: 'fork to background took ' , t printString , ' ms'; cr.
].
```

The above produces times ranging from 250 to 300 ms. I am running emulated on an ARM processor in a virtual machine on macOS so am not surprised that things are a bit sluggish, but this seems surprising.

**Comment by jgfoster** [comment]
That would explain a lot! I'm working on a rebuild now...

**Comment by jgfoster** [comment]
Yes, I was running a debug build without realizing it. It seems that the change happened about the same time I got a new machine (ARM instead of x86) and blamed it on all the performance issues. Now Jade is back to its snappy performance. Thanks so much (I'm giving a demo this afternoon at ESUG).

**Comment by blairmcg** [comment]
> UPDATE: I poked it several times and it now seems to have built without error...
> 
> My rebuild attempt gets an error: "Cannot open include file 'ActiveXHost.h': No such file or directory". I believe I'm up-to-date and did a clean and build of 7.1.

Yes, there is a project dependency issue. When switching between release/debug, you'll need to do a complete solution rebuild. Seems you got past it though.
