### ISSUE TITLE
object-arts.com won't load for me

### ISSUE THREAD

**Issue by plocket** [dolphinsmalltalk/Dolphin#1194]
**Describe the bug**
https://object-arts.com/ tries to load for a while and then says "This site can't be reached"

**To Reproduce**
1. Go to https://object-arts.com/
2. Won't load

**Expected behavior**
The site to load

**Screenshots**
N/A

**Please complete the following information):**
 - OS: Macbook Pro v12.6.6
 - Browsers:
    - Chrome v119.0.6045.105
    - Firefox v119.0

**Additional context**
N/A

**Comment by blairmcg** [comment]
object-arts.com is defunct.

**Comment by plocket** [comment]
Is there a new site?

**Comment by blairmcg** [comment]
> Is there a new site?

No
