### ISSUE TITLE
Dolphin 8.0.5 (8.0.x ?) does not start at all here under Windows 10, Germany

### ISSUE THREAD

**Issue by feldti** [dolphinsmalltalk/Dolphin#1196]
On my machine I downloaded release 7.1.27, installed it and it ran out of the box.

Then I downloaded release 8.0.5 and this version does not work at all. It mentioned, that the following libraries are not available:

msvcp140d.dll, vcruntime140d.dll and ucrtbased.dll

I assume, that the "d" means Germany and the newest runtimes from Microsoft do not deliver these language specific libraries any more ? So, what I have on my machine (system32) are:

msvcp140.dll, vcruntime140.dll and ucrtbase.dll

**Comment by blairmcg** [comment]
> msvcp140d.dll, vcruntime140d.dll and ucrtbased.dll
> I assume, that the "d" means Germany 

No, it means Debug. You would need to have VS2022 to have those installed, but for normal use it isn't a good idea to run debug Dolphin binaries anyway. That release was an experiment that should have been deleted. I might generate a usable release soon, but for now to use 8 in beta form it is necessary to follow the instructions to clone the repo and build using a free copy of VS2022 and a few minutes of effort. 

I've deleted the release, so I'm closing the bug.
