### ISSUE TITLE
Access violation exceptions when debugging Dolphin process with Visual Studio

### ISSUE THREAD

**Issue by JBetz** [dolphinsmalltalk/Dolphin#1284]
**Describe the bug**
When attached to a Visual Studio debugger, the Dolphin VM throws access violation errors during normal IDE usage. The exception doesn't get surfaced to Dolphin if you click continue, but it does happen enough to interfere with debugging.

**To Reproduce**
1. Open Dolphin image
2. Open Visual Studio and attach to Dolphin process
3. Rename a method using context menu in method pane
4. Access violation exception thrown from Visual Studio

**Screenshots**
![image](https://github.com/dolphinsmalltalk/Dolphin/assets/1424350/d7db71dd-d998-4b91-8f7d-1147c747170c)

And soon after:
![image](https://github.com/dolphinsmalltalk/Dolphin/assets/1424350/16ef2184-f0e3-4bf5-9abd-15a6bc7bfb90)

**Setup**
- OS: Windows 10
- Dolphin: 7.1.30
- Visual Studio: Microsoft Visual Studio Community 2022 (64-bit) - Current, Version 17.8.5

**Additional context**
I did notice there's an option to have Visual Studio ignore certain exception types. Is this necessary to reduce noise from exceptions that are part of normal operation?

**Comment by blairmcg** [comment]
This is not a bug. It is the use of guard pages to dynamically grow memory, similar to the example given [here](https://learn.microsoft.com/en-us/windows/win32/memory/reserving-and-committing-memory). In the first you are seeing the stack growing (or about to grow), and in the 2nd case growth of the object table. You can filter them out by module in VisualStudio to exclude the Dolphin VM, either in advance, or from that dialogue. Just tick the "Except when thrown from" box.

**Comment by JBetz** [comment]
Great, thanks!
