### ISSUE TITLE
Dolphin 7.2: CRTLibrary error when using 7.1.30 image

### ISSUE THREAD

**Issue by JBetz** [dolphinsmalltalk/Dolphin#1287]
**Describe the bug**
I installed 7.2 and opened an image I had been developing with 7.1.30, and am getting CRTLibrary errors whenever a view is opened. Maybe this backwards incompatibility is expected, but I thought it worth reporting in any case.

**Screenshots**
![image](https://github.com/dolphinsmalltalk/Dolphin/assets/1424350/3839c1b9-385c-414b-86f4-31e9223ef3cd)

**Please complete the following information):**
 - OS: Windows 10

**Comment by blairmcg** [comment]
It is expected. You can't run a 7.1 image on a 7.2 VM, or vice versa.
