### ISSUE TITLE
Package can be marked changed without discernible changes

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#13]
When loading the package 'IDB Printer' (Version 6b - November 2005), the 'Dolphin' package is marked as changed but when compared to the version in the code repository the system reports no changes. On further investigation it appears that the IDB Printer package has a preload script that adds some constants to Win32Constants, a PoolConstantsDictionary that is owned by the Dolphin package. I believe that there are a couple issues. First, by using the preload script in this way the package is essentially creating a "loose constant" (analogous to the loose method) but the source code management system does not recognize that concept and treats the change as part of another package. Second, the process of looking for changes does not seem to compare the contents of globals contained in the package to the contents of globals in the image. Thus, ignoring the change (and making it much harder to figure out why the package was changed).

**Comment by objectarts** [comment]
I think that fixing this in the correct way would be non-trivial. Given the fact that this is a rather infrequent use case and that it hasn't really been noticed up until now, I think this is fairly low priority.

**Comment by fxgallego** [comment]
Question: It's not safe memorize all changed packages before install a new package and after the install clear again all non dirty packages (those clean before install)?

Sure is low priority. I'm used before commit to check all package stars to see if there are suspicious and save all dirty packages. It's easier to verify my changes in SourceTree or GitExtensions whatever you are using. Before commit I'm used to backup my image to an ignored git folder in case the ci build fails.

**Comment by blairmcg** [comment]
Closing this as no progress has been made on it, its really only an issue with packages that are doing things they shouldn't, and in any case with Git it isn't generally a problem if the filed out content hasn't actually changed.
