### ISSUE TITLE
Is it possible to switch Dolphin 7 into dark mode?

### ISSUE THREAD

**Issue by tukanos** [dolphinsmalltalk/Dolphin#1307]
**Is your feature request related to a problem? Please describe.**
The white is hurting my eyes and I'm mostly used to darker colors.  Would it be possible to switch to dark colors without switching Windows to contrast mode?

**Describe the solution you'd like**
Switching between dark or light theme

**Describe alternatives you've considered**
I have considered Windows contrast mode, but that did not work out for me

**Additional context**
I think dark mode it healthier than the light for it reduces eye strain.

**Comment by blairmcg** [comment]
Probably not. Dolphin is a Win32 app, and Microsoft have not provided complete dark mode support for Win32, although there are a few scraps of documented support, and a bunch of undocumented work done for dark-mode Windows explorer. There are various samples and articles available that illustrate creating a dark mode win32 app (especially https://github.com/ysc3839/win32-darkmode), but I'm not sure these are really complete enough for something as wide ranging and complex as Dolphin's complete development environment, even if it would be sufficient for dark-mode in an application where the requirements are more constrained. Feel free to try out creating a solution from this and other content that can be found fairly easily, but I doubt that I will work on it as I suspect the end result will have too many gaps to be of satisfactory quality.

**Comment by tukanos** [comment]
I see.  Thank you for your detailed comment.  I'll be closing the issue for now.
