### ISSUE TITLE
Question: Status of 7.2?

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#1310]
The README.md says that 8.x is beta and 7.1 is stable. What is the status of 7.2?

**Comment by blairmcg** [comment]
It should be good, but it has had some big changes to support high DPI monitors. I thought that would be a simple thing when I started on it, but fairly soon discovered that it wasn't. Once I discovered that I then intended to go for a simpler option in 7.x than the full per-monitor support I added in 8.x, but that wasn't practical. Obviously all the tests pass, but there is a lot that isn't covered so apps and individual use cases may be broken. So over to you: Does it work for Jadeite?

**Comment by jgfoster** [comment]
I'm able to build and run Jade on 7.2 without any issues so far, so I'll use that going forward. Thanks!
