### ISSUE TITLE
Walkback when debugging complex (?) code

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#134]
Following is a simplification of my code the produces the walkback (the workaround is to move the variable declaration to outside the block):

#(1 2) do: [:each |  | a |
  [[self halt.
  a := 'AAA'.
  ] on: Error do: [:ex | ]] ensure: [ ]].

2:31:48 PM, Tuesday, March 08, 2016: 'not indexable'
Object>>errorAt:
Object>>at:
[] in Debugger>>updateTemporaries
Array(ArrayedCollection)>>do:
Debugger>>updateTemporaries
Debugger>>displayFrame
Debugger>>onFrameSelected
EventMessageSend>>forwardTo:withArguments:
EventMessageSend>>value
[] in MessageSequenceAbstract>>value
EventMessageSequence>>messagesDo:
EventMessageSequence(MessageSequenceAbstract)>>value
EventsCollection>>triggerEvent:
ListPresenter(Object)>>trigger:
ListBox(ListControlView)>>onSelectionChanged
ListPresenter(SelectableItemsPresenter)>>onSelectionChanged
ListBox(ListControlView)>>onSelChanged:
ListBox(BasicListAbstract)>>onSelChanged:
ListBox(ListControlView)>>onSelChanged
ListBox(BasicListAbstract)>>setSelectionsByIndex:
ListBox(BasicListAbstract)>>selectionsByIndex:ifAbsent:
ListBox(ListControlView)>>selectionByIndex:ifAbsent:
ListBox(ListControlView)>>selectionByIndex:
ListBox(ListControlView)>>selection:ifAbsent:
ListBox(ListControlView)>>selection:
ListBox(ListControlView)>>selectionOrNil:
[] in ListPresenter(SelectableItemsPresenter)>>selectionOrNil:
ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry
[] in ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>on:do:
ListPresenter(SelectableItemsPresenter)>>selectionOrNil:
Debugger>>populateStackModel
Debugger>>process:topFrame:
[] in Debugger class>>show:process:topFrame:resumable:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
Cursor>>showWhile:
Debugger class>>show:process:topFrame:resumable:
Process>>attachDebugger:topFrame:resumable:
Process>>debug:topFrame:resumable:
[] in Process>>walkback:topFrame:resumable:
PostedActionWindow>>evaluateNextAction
PostedActionWindow>>preTranslateMessage:
InputState>>preTranslateMessage:
InputState>>pumpMessage:
InputState>>loopWhile:
InputState>>mainLoop

**Comment by blairmcg** [comment]
This is a Compiler bug. The temps map it is returning has the wrong depth - when calculating the "outer depth" for reference to locals declared in enclosing scopes it assumes that each intervening block always has a context, but in fact this is not the case. Only full blocks will have their own contexts - blocks that don't declare any variables assigned to in nested blocks do not need a context. The compiler generates the correct instructions to take account of this, but fails to use the correct calculation when building the map of information about the temps that are in scope for ranges of instructions. I'll create a VM issue, but leave this one open to associate a unit test with.

**Comment by blairmcg** [comment]
@jgfoster, fix is finally (!) in for this in VM version 7.0.22, which has compiler fixes to correct all the problems (there were many) with temps maps. I note that there are still issues with the text maps that cause different kinds of oddities, but you should now see the correct set of temps in the debugger, and not get walkbacks from this source.
