### ISSUE TITLE
ViewComposer inspector is inadequate

### ISSUE THREAD

**Issue by blairmcg** [dolphinsmalltalk/Dolphin#142]
The ViewComposer inspector isn't really fit for purpose at either end of the property complexity scale. At the complex end (e.g. for editing Scintilla text styles) it no longer displays any custom presenters, making it necessary to open a separate inspector on the aspect in question.
At the simple, e.g. scalar property, end of the scale it is too clunky. Although the edit capability of the editable list is nice at times, very often too much clicking is necessary. One shouldn't have to double click to open a text editor and then press OK just to edit a simple property value. A more lightweight in-place edit is needed.
It also no longer offers the option of low-level editing at the instance variable level - again one has to open a separate inspector.
It was never that great, but I don't think its current incarnation is an improvement on what went before. Quite the reverse in fact.

**Comment by objectarts** [comment]
I disagree that it is worse than before. Quite the reverse in fact. IRC the changes were made for three reasons:

1) To allow simple (scalar) property editing to be done solely from the keyboard. You don't have to "double click to open a text editor" - you simply press return. The idea is that if you see a property that needs changing they you hit Enter. This will:

* Toggle the property if it can be toggled (i.e. boolean)
* Open a simple in-place editor if it has one (i.e. a single line text or a list chooser). This can also be operated from the keyboard. Enter accepts the change, Esc cancels it.
* If no specialised editor is available it opens a single line value workspace that accepts the change on Enter.

2) Allow complex UIs a known space in which to appear. Opening complex UIs in the old inspector would mean that they would often not have enough space in which to appear. The decision would have to be made (somewhere) whether a complex UI needed it's own modal dialog or should be opened in the unknown space already available in the property inspector pane. Now the decision is always that a complex UI needs a modal dialog. Yes, this has to be opened with a click (on the ...) and this would be better if a keyboard operation could do this. However, from that point on the handling of the edit can be entirely keyboard driven.

3) IIRC moving between properties in the old inspector could not always be accomplished with the keyboard where it can now.

Also, opening a separate inspector to modify instance variables seems the "correct" thing to do to me.  It is a low level task that should occur rarely (if at all) in a "property" or "published aspect" inspector.

My opinion is that the new scheme is better, looks nicer and is more in line with property editors in other development tools.

**Comment by blairmcg** [comment]
Certainly I appreciate the motivation to improve the property editing experience in the VC, and in some senses it is slicker, but there are detailed issues that I find make it frustrating to use at present. A particular example is the "transactional" nature of the property editing, whether it be by double-click or pressing Enter (after clicking in order to set focus, since keyboard navigation around the VC is always going to be complex, even if the current navigation were to be improved). Really the list should enter edit mode as soon as one navigates into a field. In the other development tools you mention you can usually just start typing to modify a string field, and there are drop-downs and other more convenient controls that don't require popping up a separate window.

As regards the instance variable inspector, I think one has to be careful to remember that much of the power of the Smalltalk IDE is the ability to look into the innards of anything and run expressions against it. In a normal IDE there isn't a general purpose way to do this kind of thing, so the developer is stuck with the property editing experience that the IDE designer is able to provide. I routinely use the basic inspector workspace to run expressions, paste things in, etc, in order to both understand what I have, and to save time. The availability of this general capability also means that it isn't necessary to go to the same extent in providing the high-level property editing capability, and so historically we haven't. One manifestation of this is that many of the less-used properties of views are not listed among the published aspects. If we wanted to provide more complete coverage here, we'd probably need to introduce some categorization of aspects to avoid overwhelming the user. At the moment our categorization is just to leave them out. 

I think it would be fine to put the instance variable inspector on another tab, just as the published aspect inspector does, and that way it has no impact on the higher-level property grid experience. Opening separate inspectors is undesirable because they are disconnected from the view being edited, so after a bit of tabbing around the user no longer knows which applies to what.

I also tend to use the inspector to browse around the properties to see not just what the current values are, but to get an idea of what they could be. This can be done by opening a full inspector, but that is hard (there is no "self" aspect to Ctrl+I on, so the only way I found to do it was to use the Visual Object Finder against the view in the view hierarchy tree), and also suffers from the problem of being detached I describe above.

Anyway, this issue is clearly too broadly drawn, so I will close it and raise some more specific issues that suggest improvements in line with the direction you are trying to take things.
