### ISSUE TITLE
ListTreeView scars badly when resizing columns

### ISSUE THREAD

**Issue by blairmcg** [dolphinsmalltalk/Dolphin#143]
![image](https://cloud.githubusercontent.com/assets/15128107/13654694/a7f174be-e651-11e5-96c2-6165c6c98861.png)

Essentially any row with empty content leaves behind the column separator as it is moved. There is also a problem with the repaint of the selected item, which gets darker and darker, also visible in the snip.

**Comment by fxgallego** [comment]
Blair,
Both problems can be resolved simply using isDoubleBuffered=true.
BTW: why inspectors are using hasGridLines=true? Looks a bit bloated and the mouse hot tracking appears to be enough.

**Comment by blairmcg** [comment]
@fxgallego, good, that does appear to be the case. Do you want to submit a PR for that?

Personally I agree the gridlines are a bit heavy. I wasn't involved with that, so I'm afraid I'm not sure why that was done. Even without the gridlines, the double buffering is still needed to correct the darkening of the selected line though.

**Comment by fxgallego** [comment]
Yes, of course.

**Comment by fxgallego** [comment]
This can be closed
