### ISSUE TITLE
TestRunner stops updating display when running long running non-UI tests

### ISSUE THREAD

**Issue by blairmcg** [dolphinsmalltalk/Dolphin#149]

**Comment by blairmcg** [comment]
The problem with ProcessTest>>testCopyExceptionHandlers is related to the fact that it creates a continuation of the main process itself, which it then resumes and terminates, potentially unwinding stuff it shouldn't. This test needs a redesign.

**Comment by blairmcg** [comment]
@jgfoster, with 7d6c3ad, you should find that the test runner now keeps updating and doesn't appear to stop on ProcessTest>>testCopyExceptionHandlers

**Comment by jgfoster** [comment]
Thanks!
