### ISSUE TITLE
IconImageManager leaks InternalIcons

### ISSUE THREAD

**Issue by blairmcg** [dolphinsmalltalk/Dolphin#155]
It looks like two equivalent InternalIcons are not considered equivalent by the IconImageManager, and therefore these leak quite badly in normal use of the class browser, etc. 
To repro, execute:

1. Open a class browser
2. Evaluate `InternalIcon allInstances size` in a workspace
3. Scroll the class tree up and down so the AbstractTutorial class goes in and out of the visible area of the tree view.
4. Repeat from 2, and note that the instance count increases each time through.

I noticed this because I was trying to debug why a GdiplusBitmap was not being released by one of the tests, and found that I had hundreds of GdiplusBitmap instances.

**Comment by blairmcg** [comment]
The problem is specifically with the "badge" icons created by some classes, as these are built dynamically by creating a blank Gdi+ bitmap in a solid colour and then drawing the internal image onto the solid background. Each instance is then unique by its #hash and #= implementations, as these defer to the blank initializer which inherits the Object implementations (identity comparison). 
Other InternalBitmaps that use the GdiplusFromBytesInitializer are fine as these use the byte array for hash/comparison purposes (although this could be inefficient for large bitmaps).
An alternate implementation of the badge form of InternalIcons would be to eschew the specific Gdi+ bitmap, and rather do the background drawing when adding to the image list. The comparison could use the bytes and the mask colour, and the intermediate bitmap would not be needed.

**Comment by objectarts** [comment]
The badge icons were really a bit of a frivolous addition and can easily be replaced by normal InternalIcons. However, the "text tile" icons introduced around the same time (and currently only used for the BetterHelloWorld class>>icon) also have the same issue. I believe the text tile icon idea is useful and may be used more in the near future. The fix introduces a TextTileIcon class with the same protocol as Icon and InternalIcon but with its own #hash and #= implementations.
