### ISSUE TITLE
Float>>printOn: results can be inexact, and may not be valid Smalltalk float literals

### ISSUE THREAD

**Issue by blairmcg** [dolphinsmalltalk/Dolphin#169]
Example: 
```
s := Float fmax printString. "'1.79769313486232e+308' - + for positive exponent is not valid Smalltalk"
Number fromString: s. "Fails with FP exception" 

```
The SmalltalkScanner/Parser also fails on this number"
`(SmalltalkScanner on: s readStream) next "->StNumberLiteral(0)"`

The compiler (which uses the CRT to read the number) reads it as "inf.0".

**Comment by blairmcg** [comment]
This is a longstanding issue. About time it was fixed.

**Comment by jgfoster** [comment]
There appears to be a problem with the runtime executable not including the C function _fpclass. Modify the following method and then deploy a Hello World (Console) application. When I run the application I get an error. 

CommandLineHelloWorld>>main
	"Implement the main body of the Headless Hello World application	
	by printing that familiar greeting to the standard output stream."

	self stdout 
		nextPutAll: 'Hello World!'; cr; flush.
	self stdout 
		nextPutAll: 'CRTLibrary default fileName in development and in runtime:'; cr; flush.
	self stdout 
		nextPutAll: ##(CRTLibrary default fileName); cr; flush.
	self stdout 
		nextPutAll: CRTLibrary default fileName; cr; flush.
	self stdout 
		nextPutAll: ##(16 sin printString); cr; flush.
	self stdout 
		nextPutAll: 16 sin printString; cr; flush.
	self stderr
		nextPutAll: 'Press <Enter> to exit:'; flush.
	self stdin nextLine


M:\Documents\Dolphin>Hello.exe
Hello World!
CRTLibrary default fileName in development and in runtime:
C:\WINDOWS\SYSTEM32\ucrtbase.dll
M:\Documents\Dolphin\Hello.exe
-0.2879033166650653
----------------------------------------Unhandled exception - a Win32Error('The specified procedure could not be found. (16r7F: The specified procedure could not be found.)')

CRTLibrary(ExternalLibrary)>>invalidCall
CRTLibrary>>_fpclass:
Float>>sign
Float>>printOn:base:
Float>>printOn:
Float(Object)>>printString
CommandLineHelloWorld>>main
CommandLineHelloWorld(SessionManager)>>mainLoopStarted
[] in CommandLineHelloWorld(SessionManager)>>forkMain
InputState>>loopWhile:
InputState>>mainLoop
[] in InputState>>forkMain
ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry
[] in ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>on:do:
[] in BlockClosure>>newProcess
----------------------------------------
****

**Comment by blairmcg** [comment]
Oops, sorry about that @jgfoster. I forgot that the togo stubs statically bind the CRT, and therefore need to export any functions required by the image. This is a bit of a maintenance problem really - it used to make sense because the CRT did not ship with Windows, so binding in the CRT avoided the need to install the runtime distributable to make an application work. Probably it should be changed now.
Anyway, in the meantime to workaround this just add an export of _fpclass to the .def files. You'll see lots of other examples there already.
