### ISSUE TITLE
ExternalProcess and KernelLibraryExtensions packages versions

### ISSUE THREAD

**Issue by fvozzi** [dolphinsmalltalk/Dolphin#197]
Hi,
we found a previous version of ExternalProcess and KernelLibraryExtensions loaded Dolphin 7. Please, see the attached images with the Dolphin 6.1 and Dolphin 7 comparison.

Please, could you load the newest or do you prefer that I do a pull request with they both?

Thanks in advance,
FV
![image2](https://cloud.githubusercontent.com/assets/9647240/15146332/1c751ae2-1691-11e6-898f-59d186e36184.png)
![image1](https://cloud.githubusercontent.com/assets/9647240/15146331/1c7232aa-1691-11e6-9c87-a9e55e8047cd.png)

**Comment by blairmcg** [comment]
PR sounds good
