### ISSUE TITLE
Cannot create MonthView control

### ISSUE THREAD

**Issue by daniels220** [dolphinsmalltalk/Dolphin#217]
Loading the "Month View" package and evaluating `MonthView new showShell` (or trying to load any view resource containing one, etc.) results in the following:

```
2016-06-30 12:52:10: 'Unspecified error (16r4005: Unspecified error)'
IDolphinAxHost(COMInterface)>>hresultError:
IDolphinAxHost(ExternalStructure)>>invalidCall
IDolphinAxHost>>CreateControlLicEx:hWnd:pStream:ppUnk:piAdvise:bstrLic:
IDolphinAxHost>>createControlLicEx:hWnd:pStream:piAdvise:bstrLic:
MonthView(AXControlSite)>>safeCreateControlFromStream:
MonthView(AXControlSite)>>createControl
MonthView(AXValueConvertingControlSite)>>createControl
MonthView(AXControlSite)>>create
MonthView(View)>>showShell
UndefinedObject>>{unbound}doIt
...
```

I have set "licenseKey" correctly as far as I can tell, and am trying this on a machine with VS2015 installed. MonthView works in Dolphin 6.0 and 6.1 on the same machine.

**Comment by blairmcg** [comment]
This is a bug in either the control or the ATL control host (it is arguable as to which). At some point between the version of ATL used in Dolphin6 and the current VS2015 version, an error check was inserted in the control activation code in atlhost.h that fails the control creation if the control returns an error code when requested to set its extend (which the month view control does for some reason). Fortunately we can work around it by providing a different implementation of the ATL code in the Dolphin AX host class that is built into the VM. We really need to re-implement this in Smalltalk, as the ATL host has many peculiarities, but for now I will add a workaround fix to the VM.
BTW: This particular control is effectively obsolete. It is

**Comment by blairmcg** [comment]
@daniels220, you should find this is fixed. If not, please re-open.

**Comment by daniels220** [comment]
Thank you! Yes, that does fix the problem. (I appreciate the explanation of the cause, as well.)

It looks like your comment above about this control being obsolete got cut off. I'm aware that the control is old and rather buggy, but I haven't found a straightforward alternative--did/do you by any chance have a suggestion?

**Comment by blairmcg** [comment]
@daniels220, sorry, I intended to say "no longer shipped with Visual Studio".
The standard Windows "Month Calendar Control" does a similar job, i.e. it allows you to see the calendar for a variable number of months (with a kind of flow layout to fill the available space), and allows you to choose a particular date. It is wrapped in Dolphin by the MonthCalendarView class.

**Comment by daniels220** [comment]
D'oh, don't know how I missed seeing that, especially since it's already there in D6—thanks for pointing it out. (Our application was originally written in Dolphin 4? Or maybe earlier? So I'm guessing we used the ActiveX version because the better one either didn't exist at all or wasn't wrapped in Dolphin yet.)
