### ISSUE TITLE
String>>at:put: causes GPFault if argument has no instance variables or slots

### ISSUE THREAD

**Issue by daniels220** [dolphinsmalltalk/Dolphin#234]
For instance, evaluate `String with: nil`. This is obviously invalid, but I would expect it to fail with `Can't hold UndefinedObject's`. Instead I get `Invalid access to memory location. Reading 0x0, IP 0x1001D7B8 (C:\Program Files (x86)\Dolphin Smalltalk 7\DolphinVM7.DLL)`. For many other objects, I do get the expected error. The critical difference seems to be, the objects that cause a GPFault have no instance variables or slots whatsoever (not even the hidden null-terminator that the empty String or Symbol have).

This isn't a critical issue—Dolphin catches and recovers from the GPFault, and an error of *some* kind clearly should occur—but if it's easy to fix, that would be nice.

GPFault:
* `nil`, `true`, `false`
* `#()`, `#[]`
* `Object new`
* `DeafObject current`
* `LargeInteger basicNew: 0`

"Can't hold" error:
* `nil -> nil`
* `OrderedCollection new`
* `#(1)`
* `1` (SmallIntegers also behave correctly, in other words)
* `''` (empty string)
* `#''` (empty symbol)

**Comment by blairmcg** [comment]
Fixed. You need VM v7.0.25

**Comment by daniels220** [comment]
Nice, thanks.
