### ISSUE TITLE
ByteArray>>itcAsInteger uses wrong endian order

### ISSUE THREAD

**Issue by bernhardkohlhaas** [dolphinsmalltalk/Dolphin#294]
The implementation of ByteArray>>itcAsInteger treats the first byte as MSB, however I believe that the first Byte should be the LSB, so that the result is equal to 'wordAtOffset: 0' or 'dwordAtOffset: 0' (for array sizes 2 and 4 respectively).

Therefore I suggest that the iteration should be done in reverse order.

Proposed implementation:

    ByteArray>>itcAsInteger

    	"Since the LSB is at index 1, we need to reverse iterate over the receiver"

    	| answer |
    	answer := 0.
    	self reverseDo: [:each | answer := answer * 256 + each].
    	^answer

**Comment by blairmcg** [comment]
As discussed in the PR, this may be because it is designed for portability across platforms.
