### ISSUE TITLE
Walkback "Undefined object does not understand #selector", when saving method with syntax error

### ISSUE THREAD

**Issue by bernhardkohlhaas** [dolphinsmalltalk/Dolphin#299]
When I save the following method (use any class), I'm getting a walkback:

    test
        1 to: 10 do: [:index 2 | index2]

Obviously the method has a syntax error due to the extra space between :index and 2, but perhaps the error could be handled more gracefully, like other syntax errors are.

**Comment by blairmcg** [comment]
Good catch. Seems that the compiler is detecting the error and not generating a method, but not reporting a syntax error.
