### ISSUE TITLE
Unable to version package from SystemBrowser

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#3]
PackageSelector (in PackagedClassSelector in SystemBrowserShell) has a context menu with the #'versionPackage' command (plus a couple others that don't work either). This method is implemented only in PackageBrowserShell, which is not present in SystemBrowserShell.

**Comment by objectarts** [comment]
Fixed in [commit](https://github.com/dolphinsmalltalk/Dolphin/commit/9c2a78367711fb276ca8b3a7a59b7da232a5cc58).
