### ISSUE TITLE
BootDPRO.cmd failing to create Dolphin Pro image

### ISSUE THREAD

**Issue by brunobuzzi** [dolphinsmalltalk/Dolphin#301]
Error at:
https://github.com/dolphinsmalltalk/Dolphin/blob/master/Core/Object%20Arts/Dolphin/IDE/Community%20Edition/Dolphin%20Community%20Edition%20Tools.pax

Line 29 is:
version := ScintillaLibrary versionString.
But should be:
version := ScintillaLibrary default versionString.

The problem after this change is the script answer (line 34):
'http://www.scintilla.org/wscite3630.zip'
But this file does no exist anymore in Scitilla site.

The file wscite363.zip it does exist.

**Comment by brunobuzzi** [comment]
Changing the file name to **wscite363.zip** let **BootDPRO.cmd** finish its job.
But if you try to open a Dolphin imagen then:
10:26:45, viernes, 27 de enero de 2017: 'The specified procedure could not be found. (16r7F: No se encontró el proceso especificado.)'
ScintillaLibrary(ExternalLibrary)>>invalidCall
ScintillaLibrary>>directFunction:msg:wParam:lParam:
ScintillaView>>sendMessage:wParam:lParam:
ScintillaView(ControlView)>>setFont:
ScintillaView>>setFont:
ScintillaView(ControlView)>>onViewCreated
ScintillaView(ValueConvertingControlView)>>onViewCreated
ScintillaView(TextEdit)>>onViewCreated
ScintillaView>>onViewCreated
ScintillaView(View)>>createAt:extent:
MessageSend(MessageSendAbstract)>>value
[] in MessageSequenceAbstract>>value
OrderedCollection>>do:
MessageSequence>>messagesDo:
MessageSequence(MessageSequenceAbstract)>>value
ScintillaView(View)>>state:
ScintillaView(STBViewProxy)>>restoreView
ScintillaView(STBViewProxy)>>restoreTopView
[] in ScintillaView(STBViewProxy)>>stbFixup:at:
[] in STBInFiler>>evaluateDeferredActions
OrderedCollection>>do:
STLInFiler(STBInFiler)>>evaluateDeferredActions
STLInFiler(STBInFiler)>>next
ResourceIdentifier>>loadWithContext:forEdit:
ResourceIdentifier>>loadWithContext:
ReferenceView>>loadReferee
ReferenceView>>referee
ReferenceView>>createDelegate
ReferenceView(AbstractDelegatingView)>>onViewCreated
ReferenceView(View)>>createAt:extent:
MessageSend(MessageSendAbstract)>>value
[] in MessageSequenceAbstract>>value
OrderedCollection>>do:
MessageSequence>>messagesDo:
MessageSequence(MessageSequenceAbstract)>>value
ReferenceView(View)>>state:
ReferenceView(STBViewProxy)>>restoreView
[] in STBViewProxy>>restoreView
Array(ArrayedCollection)>>do:
Toolbar(STBViewProxy)>>restoreView
Toolbar(STBViewProxy)>>restoreTopView
[] in Toolbar(STBViewProxy)>>stbFixup:at:
[] in STBInFiler>>evaluateDeferredActions
OrderedCollection>>do:
STLInFiler(STBInFiler)>>evaluateDeferredActions
STLInFiler(STBInFiler)>>next
ResourceIdentifier>>loadWithContext:forEdit:
ResourceIdentifier>>loadWithContext:
ReferenceView>>loadReferee
ReferenceView>>referee

**Comment by brunobuzzi** [comment]
Workaround:
1- Remove the Post Install script from https://github.com/dolphinsmalltalk/Dolphin/blob/master/Core/Object%20Arts/Dolphin/IDE/Community%20Edition/Dolphin%20Community%20Edition%20Tools.pax 

2- Execute BootDPRO.cmd or BootAll.cmd (to rebuild everything)
3- Copying by hand the SciLexer.dll version 372 to Dolphin directory.
Dolphihn runs without problem :)

**Comment by blairmcg** [comment]
Bruno, it is working fine on all the AppVeyor builds and locally for me. As you didn't post information about the original error, I'm not quite sure why it isn't working for you. The upgrade script could fail if the Scintilla site is down, or if the SciLexer.dll on disk is locked or read-only for some other reason. If you experience a problem with the Scintilla upgrade check in the boot, I'd recommend just deleting SciLexer.dll from the disk and trying again. This will replicate the clean build scenario (at lest for this bit) that applies for the AppVeyor build.
The script is correct as is - it uses a version number generated into the class to work out which version of the Scintilla DLL is needed, and then checks the version you have. If the versions do not match, it downloads the expected version from scintilla.org. If you change it to `version := ScintillaLibrary default versionString`, then it will attempt to load and use the version of the library on the disk. There is of course no point using the version number of the library you already have to check if you have the right version :-). The version number is not in the expected format anyway (hence the 3630). The result you see in your 2nd comment is one of those one might expect if the wrong version is present (which it will be, if you unzipped 363 as that is significantly out of date).

**Comment by brunobuzzi** [comment]
Blair,
This is the original error (still happening to me): (Error trying to download Scintilla)
Loading source package 'Dolphin Community Edition Tools' from: C:\Users\Usuario\
Documents\GitHub\Dolphin\Core\Object Arts\Dolphin\IDE\Community Edition\Dolphin
Community Edition Tools.pax
----------------------------------------Unhandled exception - a HRESULTError('HR
ESULT Error: Error en la descarga del recurso solicitado. (Unknown facility)')
URLMonLibrary(ExternalLibrary)>>invalidCall
URLMonLibrary(InputState)>>isInputAvailable
URLMonLibrary>>urlDownloadToCacheFile:
Package>>{unbound}doIt
Compiler class>>evaluate:for:evaluationPools:logged:ifFail:
Compiler class>>evaluate:for:evaluationPools:logged:
Compiler class>>evaluate:for:logged:
[] in ChunkSourceFiler>>fileIn
ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry
[] in ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>on:do:
ChunkSourceFiler>>fileIn
[] in Package>>fileInScript:
ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry
[] in ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
----------------------------------------

**Comment by bernhardkohlhaas** [comment]
@brunobuzzi FWIW, it also works fine for me on a fresh clone from Dolphin (using Windows 10 Pro 64-bit, v1511). 

So it looks like something might funky with your local system. At the risk of stating the obvious, here are the exact steps I executed:

1. Use git bash shell to create a new directory, go to that directory and clone Dolphin into it ("git clone https://github.com/dolphinsmalltalk/Dolphin.git")
2. Open Windows PowerShell as Administrator to execute "Set-ExecutionPolicy remotesigned"
3. In git bash shell go to newly cloned Dolphin directory and execute "./FetchVM.cmd"
4. In Windows PowerShell (still in Admin mode) execute "Set-ExecutionPolicy undefined" (I prefer to turn that setting off, unless I need it)
5. In git bash shell execute "./BootDPRO.cmd"

I also analyzed the http traffic with Fiddler and during the BootDPRO script a request to www.scintilla.org/wscite371.zip is sent successfully. Initially I got a 304 response, because the file was already in my local IE cache, but even after clearing the IE cache I got the proper 200 status code, so the file is available.

Perhaps you could clear your IE cache and try it again on a clean git clone. If it still doesn't work, then trace the http traffic with Fiddler.

**Comment by brunobuzzi** [comment]
After uninstalling NotePad++, Dolphin 6.1 and others i get the correct Scintilla version.
But my machine fail with:
URLMonLibrary default urlDownloadToCacheFile: 'http://www.scintilla.org/wscite371.zip'.

18:01:53, martes, 31 de enero de 2017: 'HRESULT Error: Error en la descarga del recurso solicitado. (Error downloading requested resource)(Unknown facility)'
URLMonLibrary(ExternalLibrary)>>invalidCall
URLMonLibrary(InputState)>>isInputAvailable
URLMonLibrary>>urlDownloadToCacheFile:
UndefinedObject>>{unbound}doIt

If i put "http://www.scintilla.org/wscite371.zip" in any browser i can download the Zip file.
Event inside Dolphin (where the above fail) with the WebBrowserShell i can download the Zip file.
So something wrong with URLMonLibrary ? Still researching...

**Comment by bernhardkohlhaas** [comment]
Are you by any chance behind a firewall that requires a proxy server?

**Comment by brunobuzzi** [comment]
Oh Yes. 
It was the **Avast antivirus** causing the error.
D7 Pro image built without problems :)
