### ISSUE TITLE
Class GUID now has lowercase hex characters

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#321]
Saving an otherwise unmodified package now shows every class definition as edited because the CLS definition has a lowercase GUID instead of uppercase. Was this intended?

**Comment by jgfoster** [comment]
This change was introduced by eaf8459 and removed the following line from GUID>>#idlString'.
`UserLibrary default stringUpperA: pSz.`
I can see that removing this line makes things faster, but at the cost of false positives on edits.

**Comment by blairmcg** [comment]
The change to GUID>>idlString was deliberate. I was aware of this resulting in changes to class files, but as it is a one-off effect it will stabilise out quickly (like the version comment at the top) so I didn't think it mattered enough to worry about.

**Comment by jgfoster** [comment]
How would you feel about a pull request with all the packages re-saved to get the version and GUID changes over with?

**Comment by blairmcg** [comment]
Seems like a fine idea James.
