### ISSUE TITLE
Dolphin7.exe fails to open the default image, when started without arguments

### ISSUE THREAD

**Issue by FunctionPoint** [dolphinsmalltalk/Dolphin#38]
Hi everyone,      (I'm RichardR on c.l.s.dolphin)

Here is my first contributing issue+fix to Dolphin 7.
I will continue later with a Github fork and pull request, also a first for me.

====
Issue: 

Dolphin7.exe, when started without arguments,  fails to open the default image "Dolphin.img7" in the same folder.
This functionality is good to have in VM development, when you want to be sure you are using the right (development) VM exe.
It's also handy for (test) deployments that don't use Lagoon. E.g.: Where you deploy an image without stripping the dev env.

The fix is in two places, specified below, with original code commented out.
1 - Change assert that there must be at least two command line arguments
2 - Check before parsing over the "image" command line argument if it was given.

Any comments before proceding?

Cheers,
Richard

==== Proposed sourcecode:

CommandLine>>initialize: anArray

	argv := anArray.
	"self assert: [2 <= argv size]."
	self assert: [argv size >= 1].	"Fix: argv size 1 is OK, open default image"
	optIndex := 1.
	optionPrefixChars := '-/'.

CommandLine>>parse

	arguments := OrderedCollection new.
	options := OrderedCollection new.
	parsingArgStream := (ReadStream on: argv) 
		next; 	"exe"
		"next;" 	"img7"   "Fix: Don't assume image name is 2nd argument"
		yourself.

	parsingArgStream atEnd ifFalse: [	"Parse and discard image name" 
		parsingArgStream next. ].

	[parsingArgStream atEnd] whileFalse: [	"iterate over the argv array"
		self parseNextArg.
	].
	arguments := arguments asArray.

**Comment by FunctionPoint** [comment]
Hah @jgfoster ,
With your recent fix "CommandLine fix for runtime #42" you almost also fixed this issue.
When Dolphin7.exe it now opens Dolphin.img7 (with DRPO.* renamed to Dolhin.*).
But behind the splash screen there is a walkback error window:
![error](https://cloud.githubusercontent.com/assets/9684694/12460810/e9db3fa8-bfb5-11e5-9f25-a706dc592d4b.png)

The culprit is:
DevelopmentSessionManager>>processCommandLine
     ...
	arguments := commandLine arguments allButFirst. "leave off image name"
     ...

Where "allButFirst" fails because the "commandLine arguments" returns an empty array. (no arguments)

James: You you want to fix this one yourself?

Cheers, Richard

**Comment by jgfoster** [comment]
@FunctionPoint, Thanks. See https://github.com/dolphinsmalltalk/Dolphin/pull/45.

**Comment by FunctionPoint** [comment]
Fixed by @jgfoster in: Fix problem if no image name provided #45
