### ISSUE TITLE
Add primality test to class Integer "isPrime"

### ISSUE THREAD

**Issue by FunctionPoint** [dolphinsmalltalk/Dolphin#391]
This is a small feature addition, 
mainly to get me started in the process of  Dolphin open source development.
I've already written the code and a new test for it.
@blairmcg : I'm getting an authentication error when trying to publish my locally committed branch to the Dolphin repo. Do I need some special access, or am I missing something? (PS Using GitHub Desktop beta)

**Comment by rejurime** [comment]
I don't know if this helps but the steps are:
* Fork Dolphin repository
* Make your changes locally
* Push to your Github repository
* Make a Pull request to Dolphin respository

This links can help you:
* https://guides.github.com/introduction/flow/
* https://help.github.com/articles/github-flow/

**Comment by blairmcg** [comment]
Yes, that is right. Like most public open source repo's on GitHub, you can't push to it directly unless you are maintainer. You have to work in a fork, and PR into the "upstream". GitHub makes this very easy though, and it has the additional benefit that your experiments and work in progress won't appear in the base repo (unlike mine, ahem, as I keep forgetting to push to my fork).
You are encouraged to first create an issue, as you have done, and cross reference it from the PR you submit.

**Comment by FunctionPoint** [comment]
Thank you, Blair & Rene, I was missing the "fork" step. Have committed to a forked branch now and have created my first public pull request :)
