### ISSUE TITLE
Pen and Touch not working in Windows 8.1 and 10

### ISSUE THREAD

**Issue by andygraham** [dolphinsmalltalk/Dolphin#404]
On Windows 7 Dolphin appears to work fine with Touch, Pen and Mouse input. However on Windows 
8/8.1/10 only Mouse input works correctly. 

After digging deep into Dolphin Windows message handling I found that the problem lies with the value of the QS_ALLINPUT flags value used by isInputAvailable. This is defined in the Win32Constants pool dictionary. The default value is 16rFF which is the pre Windows XP value. Windows XP and later support an extra flag, 16r400, which allows applications to detect raw input messages from some HID devices like joysticks or 3D mice. Examining the return of the GetQueueStatus call in isInputAvailable I observed a totally uncocumented flag, 16r1000 which appears when the pen or touch events occur. Adding this to  QS_ALLINPUT worked!

So in the only change needed to get pen and touch events working in Windows 8/8.1/10 is to change the value of  QS_ALLINPUT to a value of 16r10FF or 16r14FF and accept the “recompile methods?” message that Dolphin throws up.

**Comment by blairmcg** [comment]
@andygraham, yes that is part of the solution. We also need to change the definition of _WIN32_WINNT in the VM build as it is building to target Windows pre-version 6 currently. Without changing that the system won't recognise incoming events from those sources when it is doing heavy background computations. It will mostly work though if you just change the constant in the image.

The most up to date definition is:
```
#define QS_INPUT           (QS_MOUSE         | \
                            QS_KEY           | \
                            QS_RAWINPUT      | \
                            QS_TOUCH         | \
                            QS_POINTER)
...
#define QS_ALLINPUT        (QS_INPUT         | \
                            QS_POSTMESSAGE   | \
                            QS_TIMER         | \
                            QS_PAINT         | \
                            QS_HOTKEY        | \
                            QS_SENDMESSAGE)
```
QS_TOUCH is 16r800, and QS_POINTER is 16r1000. You are right that the latter two don't seem to be documented, but they are in the WinUser.h header file from the Windows SDK.
Therefore QS_ALLINPUT should be 16r1CFF for windows 6.02 (Windows 8.0) and later

**Comment by jgfoster** [comment]
And with this we are no longer supporting Windows 7 (https://github.com/dolphinsmalltalk/DolphinVM/issues/135)?

**Comment by blairmcg** [comment]
No, of course that isn't the intent. Microsoft's mainstream support for Windows 7 has ended, but it is in extended support until January 2020. In the meantime, however, if you track the tip of master you might very well encounter issues on that platform, since it isn't a mainstream dev/test platform any more, so any issues aren't going to show up in the regular CI builds, even if they have test coverage. Of course the test coverage is variable, and even if it weren't it should still be assumed that the development tip is "unbaked".

**Comment by jgfoster** [comment]
Sorry, my question was a bit harsh. I completely recognize the risks associated with staying on the "bleeding edge" and enormously enjoy my experience being out front even if it does involve the occasional setback. Thanks for your patience!
