### ISSUE TITLE
Ctl+Break not entering debugger

### ISSUE THREAD

**Issue by andygraham** [dolphinsmalltalk/Dolphin#410]
If I perform '30000 factorial' in a workspace I can't seem to interrupt it and enter the debugger with Ctl+Break. I've tried several keyboards but it doesn't seem to work. Should it? Perhaps I'm being stupid and missing something!

Is it possible to set a different key combination to activate the debugger?

**Comment by rko281** [comment]
The user interrupt key combination was changed to Ctrl+F12 in #144, however some comments still reference Ctrl+Break (e.g. SessionManager>>onUserBreak).

**Comment by andygraham** [comment]
"however some comments still reference Ctrl+Break (e.g. SessionManager>>onUserBreak)."

As does the chm Help file! Many thanks for the info.
