### ISSUE TITLE
Chunk Browser buttons are missing bitmaps

### ISSUE THREAD

**Issue by andygraham** [dolphinsmalltalk/Dolphin#422]
The bitmaps for some of the buttons on the Chunk Browser toolbar are missing from the image as they are loaded from a Core\Contributions\IDB\Resources folder which doesn't exist after installing Dolphin or saving an image.

Luckily pedantic little me squirrels things away and I found a copy of Idbgoodies6g.zip in my backups that contains that folder so I got them back by opening a Package Browser and finding Contributions -> IDB -> IDB Chunk Browser and saving it. I then found the IDB Resources folder in the Idbgoodies6g.zip, copied it to Core\Contributions\IDB where IDB Chunk Browser.pac is located, restarted the image and voila!

**Comment by jgfoster** [comment]
@andygraham, are you planning to share this so we can benefit from your discovery?

**Comment by andygraham** [comment]
Here you are.
[Resources.zip](https://github.com/dolphinsmalltalk/Dolphin/files/1172851/Resources.zip)

**Comment by blairmcg** [comment]
These are in the main repo anyway, though apparently not deployed by the installer. I'm afraid the setup isn't something I want to spend time on, but it could either be fixed there, or the resources internalised using e.g. the InternalBitmap stuff, if that can be made to work in this case.

**Comment by blairmcg** [comment]
@jgfoster has fixed this.
