### ISSUE TITLE
GPFault generating GUID on startup

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#437]
I'm having trouble with a runtime on Windows 7. If I use the startTime instead of a GUID then the runtime startup works (see #417 and #423). 

[GPFault.txt](https://github.com/dolphinsmalltalk/Dolphin/files/1192178/GPFault.txt)

**Comment by blairmcg** [comment]
Ah, I'd not noticed where you'd added the `sessionId := GUID newUnique.`. It is too early. It has to be done after `SessionManager>>openLibraries` is called. No external library functions should be called before that point.  I would put it at the end of `SessionManager>>basicPrimaryStartup`
