### ISSUE TITLE
Problem in OVERLAPPED class>>defineFields?

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#454]
As far as I can tell, all the ExternalStructure definitions that contain a union, except OVERLAPPED, use #defineField:offset: to create their fields (see, e.g., IN_ADDR). In OVERLAPPED class>>defineFields uses #defineField: without an offset, so the default behavior is to just keep appending fields (I believe). I think that this will cause all but the first union element and everything after the union to be misplaced. 

I'm not needing this structure, but I was looking for examples of how to construct a union and this seems wrong. Am I missing something?

**Comment by blairmcg** [comment]
Yes, @jgfoster, you are right. This is incorrectly defined. Well spotted. I will just regenerate it from a Win32 typelib project I have. At some point I will publish it so others can use it. In the meantime if you need any Win32 structures let me know and I can usually generate them using the AX Component Wizard, which is much quicker and less error prone than building them by hand.

The right way to do union's, as you have worked out, is to specifying overlapping offsets for the union fields.
