### ISSUE TITLE
Examples in "A First Splash with Dolphin" can't be copied and pasted into workspace.

### ISSUE THREAD

**Issue by oofoe** [dolphinsmalltalk/Dolphin#467]
Despite instructions to the contrary, the text marked with yellow backgrounds in the introductory tutorial can't be copied and pasted to a workspace to be evaluated.

Example on this help page: mk:@MSITStore:C:\Program%20Files%20(x86)\Dolphin%20Smalltalk%207\EducationCentre7.chm::/big_numbers.htm

Tried copying and pasting into different applications (Notepad++, Emacs, etc.) and it seems like the copy event is never processed by help viewer (paste puts down whatever I previously copied from other applications). Tried on Windows 7 and Windows 8 machines.

I wound up typing everything in manually, and while this is not _too_ onerous, the instructions should be updated at least for the intended beginner audience.

Thanks!

**Comment by blairmcg** [comment]
@oofoe, this appears to be an issue local to your machine/setup. It works fine for me using either the keyboard shortcut or the context menu in the help app.

**Comment by oofoe** [comment]
Revisited help app, context menu copy does work (did not think to test that earlier, I'm used to the shortcut), but Ctrl-C did not.

Copy and paste worked fine from the Workspace and Package Browser editor.

Windows 7, Dolphin Image 7.0.39 if that helps.

Thanks for looking into it!
