### ISSUE TITLE
Any plan for stable release with bug fixes and a separate new feature fork?

### ISSUE THREAD

**Issue by cDemersMitSci** [dolphinsmalltalk/Dolphin#472]
I really appreciate that Dolphin is now Open Source and actively being developed.  Thank you! Once I become more familiar with GitHub I hope to contribute to the effort.

As someone developing a product with Dolphin it has been a challenge to use Dolphin 7 while adapting to a mix of significant changes, bug fixes, and new bugs in different releases.  Object Arts used to release major upgrades with new features and changes.  Then there would be minor bug-fix patches.  This provided a very stable development platform.  I appreciate that maintaining different forks with fixes is more difficult, but it does make it much easier to manage application releases. 

I initially started using Dolphin 7.0.05. Eventually I encountered the bug that caused the image to crash when empty ActiveX collections were accessed.  So I upgraded to 7.0.39.  The collection bug was fixed, but the STB format was also upgraded.  I use that for some object persistence in my application, so now users can't downgrade and open files saved in the new version.  I also can't load new views back into an older version.  Then there was an intermittent problem with edit focus on EditableListViews.  That seems to be fixed in the 2017/10/09 build, but now I'm using a daily release and I've had to workaround a change in behavior affecting proxied objects in TreeViews (not sure if it is a bug).

I haven't yet widely released the Dolphin 7 version of my application yet, but I will need to release something soon.  

Is there a plan to reach some feature base level and maintain it with bug fixes with new features forked into a new version?

**Comment by blairmcg** [comment]
Being completely honest, no, at least not from me. I can understand the need for that, but it is not something I want to spend my time on personally since this is a hobby project for me these days. You are free to maintain your own stable fork of course, perhaps with anyone else with a similar need. This would be easy to do (mechanically) with git/GitHub.

Regarding the forward-compatibility issue with STB, you could back port the code into D6, or raise a separate issue to refactor the code in D7 and add support for outputting the downlevel format.

**Comment by cDemersMitSci** [comment]
Thanks for responding.  That make sense.  

When the next stable release from GitHub occurs I will attempt to maintain it with important bug fixes. My intent would be to keep a feature stable fork for 6-12 months and then do the same with a new mainstream build.  I might be able to use the concept of patch levels on an initial version, like OA used to, to avoid version confusion.

I think I can manage STB compatibility so long as I commit to solving problems by only moving forward.

**Comment by blairmcg** [comment]
@cDemersMitSci, closing this as it is more of a question, and I think answered.
