### ISSUE TITLE
Debugger shows less useful info first

### ISSUE THREAD

**Issue by FunctionPoint** [dolphinsmalltalk/Dolphin#488]
The debugger always shows "self" first with the following indented fields: 
superClass, methodDictionary, instanceSpec, subclasses, instanceVariables, methodsCatalogue, protocols, name (duplicate anyway) classPool, sharedPools, comment (ID) classCategories and _guid.
.
With the expection of "instanceVariables", these are static and so less usefull fields when debugging. 
Below "self", the more usefull info is displayed: Local variables and the stack.
Now you always have to scroll down to see them everytime you hit a bearkpoint.
.
Could "self" be moved to the bottom om the (default) debug display?

**Comment by fxgallego** [comment]
Yes, I think the you're right. Maybe the variables pane could be splitted in All, instance vars, local vars using a tab control.

**Comment by blairmcg** [comment]
Fixed by da42a1c for Dolphin 8. I won't be backporting it myself.
