### ISSUE TITLE
HttpApi: Provide ReceiveRequestEntityBody example

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/Dolphin#489]
I've been working on a high level wrapper for the new Dolphin's HttpServerApi interface.
I've tried several things to emulate the msdn example https://msdn.microsoft.com/en-us/library/windows/desktop/aa364640(v=vs.85).aspx and I could not make any of them work.
I'm testing with POST requests with a body of 1500 bytes (only A chars).

My code for receiveEntityBody is
```
receiveRequestEntityBody: anExternalHandle requestId: requestId
	| bytesReceived buf bufLen data |
	bufLen := 1024.
	buf := ByteArray new: bufLen.
	data := WriteStream on: (ByteArray new: buf size).
	bytesReceived := DWORDBytes new.
	
	[| ret |
	ret := self
				asyncReceiveHttpRequestEntityBody: anExternalHandle
				requestId: requestId
				flags: WinHttpServerConsts.HTTP_RECEIVE_REQUEST_ENTITY_BODY_FLAG_FILL_BUFFER
				entityBuffer: buf
				entityBufferLength: buf size
				bytesReturned: bytesReceived
				overlapped: nil.
	ret == Win32Errors.ERROR_INVALID_PARAMETER
		ifTrue: 
			[self checkReturnCode: ret.
			^buf]
		ifFalse: 
			[ret == Win32Errors.NO_ERROR
				ifTrue: [
					data nextPutAll: (buf copyFrom: 1 to: bytesReceived asInteger).
					buf := ByteArray new: bufLen]
				ifFalse: 
					[
					ret == 38 "EOF"
						ifTrue: [^data contents]
						ifFalse: 
							[self checkReturnCode: ret.
							^data contents]]]]
			repeat

```
```
asyncReceiveHttpRequestEntityBody: requestQueueHandle requestId: requestId flags: flags entityBuffer: entityBuffer entityBufferLength: entityBufferLength bytesReturned: bytesReturned overlapped: overlapped
	"Invoke the HttpReceiveRequestEntityBody() function of the module wrapped by the receiver.

		ULONG __stdcall HttpReceiveRequestEntityBody(
			[in]HANDLE RequestQueueHandle,
			[in]unsigned __int64 RequestId,
			[in]ULONG Flags,
			[out]void* EntityBuffer,
			[in]ULONG EntityBufferLength,
			[out]ULONG* BytesReturned,
			[in]LPOVERLAPPED OVERLAPPED);"

	<overlap stdcall: dword HttpReceiveRequestEntityBody handle qword dword void* dword dword* OVERLAPPED*>
	^self invalidCall
```
I've implemented an adapter for Seaside and I'm very close to get Seaside to work with this server but I can't get POST data. It's not clear to me whether I can receive the payload in pEntityChunks or I need always to end using ReceiveRequestEntityBody. Note that HTTP_REQUEST_FLAG_MORE_ENTITY_BODY_EXISTS is present in the request received by #receiveRequest:, but the call to ReceiveRequestEntityBody returns EOF and 0 bytes read.
I've tested changing in #receiveRequest: the request flag from `WinHttpServerConsts.HTTP_RECEIVE_REQUEST_FLAG_COPY_BODY` to `0` as in the msdn example without effects.
Also, when the payload is in pEntityChunks it is incomplete.

**Comment by fxgallego** [comment]
My code for receive the entity body was ok. The problem was that I made a mistake calling 2 times the receiveEntityBody api unintentionally. I'll try to provide a PR with the method additions and examples.

**Comment by blairmcg** [comment]
Glad you were able to get it working. My impression is that this API is designed with performance as an overriding consideration - ease of use takes a back seat. It's hard to get it right.

**Comment by fxgallego** [comment]
@blairmcg I had to use the [HttpReceiveRequestEntityBody](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364496(v=vs.85).aspx) in order to get the request body. In your `HttpApiLibrary>>receive:` implementation you are using the `HTTP_RECEIVE_REQUEST_FLAG_COPY_BODY` flag. But it doesn't works the way it's expected (neither `HTTP_RECEIVE_REQUEST_FLAG_FLUSH_BODY`. At least not from the Dolphin side. Using curl you can test that, when a file is uploaded, pEntityChunks is empty  and the flag `HTTP_REQUEST_FLAG_MORE_ENTITY_BODY_EXISTS ` is present.
Sending a big data value instead of a file produces the same result. Only sending small chunks of data works ok. Maybe there is something missing in the #receive: implementation.
The [HttpReceiveHttpRequest](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364495(v=vs.85).aspx) remarks section explains how to use HttpReceiveHttpRequest or HttpReceiveRequestEntityBody to get the additional data.

At the end I was able to get the body, including file uploads of more than 100MB passing 0 to the HttpReceiveHttpRequest flags and retrieving the body with HttpReceiveRequestEntityBody as the remarks section say. I have not implemented chunked transfer so really big file uploads are not possible yet.
I think maybe the pEntityChunks member would be useful for that but I'm not sure. It's no clear to me from the docs. I'm afraid of losing something useful changing the current flag to 0.
Anyway I'm ready to share the code for review.

I've used the following curl commands to test (from git bash console):
```
curl --data "param1=value1" http://localhost:8080/Test
cat large.csv | curl -d @- http://localhost:8080/Test
curl --form "fileupload=@400K-file.zip" http://localhost:8080/Test
```

**Comment by blairmcg** [comment]
`HttpApiLibrary>>receiveRequest:` is just an example and wasn't written with receiving large uploads in mind. Reading the docs carefully the `HTTP_RECEIVE_REQUEST_FLAG_COPY_BODY` flag is going to retrieve only the **available** body, so for a large request that isn't going to be the whole request. I agree with you that the docs appear to state that by using `HTTP_RECEIVE_REQUEST_FLAG_FLUSH_BODY` one should get the whole thing, however perhaps the docs are overpromising there and there are limits to what the API will attempt to return in one go. There would be some sense in that as you might end up blocking for an arbitrarily long time, and in a 32-bit process you could easily run out of memory as well.
I think it would really make sense to implement a proper streaming mechanism to handle large requests in pieces, but in the meantime what you've done sounds sensible. I expect you'll lose some perf for smaller requests, however, and so perhaps it would make sense to keep the flag as is and only call HttpReceiveRequestEntityBody when the request flags indicate there are further entity body parts to retrieve.

**Comment by fxgallego** [comment]
I think the new Dolphin HTTP Server packages has a good example in its HttpServerRequest class.
