### ISSUE TITLE
(UnicodeString fromString: 'foo') = 'foo' returns false

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/Dolphin#490]
I don´t know if this is a bug or a feature.
But I'm working with the url returned from the HTTPApiLibrary and can't compare strings safely without taking into consideration the conversion to a proper String. Think that's not a good thing.

Udo Scheneider's UnicodeString extensions provides useful methods and solves this problem. Maybe that code could be merged to the base. It would require some work to adapt to the new Character codePoint.

Any thoughts?

**Comment by blairmcg** [comment]
Yes, that sounds inconvenient. The whole <String> hierarchy is really in need of refactoring to separate out the notion of string-ness into an abstract base with byte and wide subclasses. That's a fairly major undertaking, however, and will be difficult to make bootable, so we'll have to go for something simpler for now. I'll see what I can do with a bit of double-dispatch...

**Comment by blairmcg** [comment]
Fixed in ea92b8a
