### ISSUE TITLE
HttpClient doesn't works

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/Dolphin#496]
HttpClient getUrl: 'http://www.google.com/' gives me a message not understood because it expects #webHttpClientSocketToClose: to be defined in Process. It appears that some Process extensions are lost.

This applies to EmailSMTPConnector as well.

BTW: I think that ITC Gorisek packages define too much extensions and not always is clear why we need them, for example Timestamp. IMO STS shouldn't be loaded by default this days.

**Comment by blairmcg** [comment]
The HTTPClient has been removed from the standard build
