### ISSUE TITLE
Adding Utf16String to WriteStream on String goes badly

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#508]
| stream |
stream := WriteStream on: String new.
stream
	nextPutAll: 'Jade 2 (DataCurator) ';
	nextPutAll: (Utf16String withAll: 'gemstone4');
	nextPutAll: ' with session 2 on localhost';
	contents.
"Jade 2 (DataCurator) g?e?m?s?t with session 2 on localhost"

**Comment by blairmcg** [comment]
Yes, this is one of the major issues that needs to be dealt with before switching over to Unicode views entirely - the Streams are not encoding aware. There are lot of other minor issues, and no doubt a lot more we aren't aware of yet, but this is one of the most important.

**Comment by blairmcg** [comment]
Addressed in 7.1 (note this is not merged in to master yet). 

![image](https://user-images.githubusercontent.com/15128107/39836008-f130590a-53c9-11e8-86f4-e3250d6f2882.png)

BTW: The result is a Utf8String, as that is now the default String type. String itself is abstract.
