### ISSUE TITLE
Process does not understand #webHttpClientSocketToClose

### ISSUE THREAD

**Issue by Debiller777** [dolphinsmalltalk/Dolphin#514]
So HttpClient class has class method "getUrl", however when I call it I get error that Process doesnt understand method "webHttpClientSocketToClose". So I decided to browse it. My try was unsuccessful. Then I decided to browse all references to this method. It turned out that Process>>itcSafeTerminate used 
this method and sent it so self, though it wasnt implemented. Also it it used another undefined method "asWebString". So, what should I do? Where can I find sources of these methods.

**Comment by blairmcg** [comment]
The package is a third party contribution that hasn't been imported completely, or is missing dependencies. Given the absence of tests, there is little guarantee it will work even with the missing pieces. Someone will need to volunteer to fix it, or I would be happy to remove it.

I'm not sure how practical it is, or how much use it has received, but there is a wrapper around the Microsoft HTTP client through IWinHttpRequest, e.g

```
http := IWinHttpRequest new.
http open: 'get' url: 'http://www.google.com'.
http send.
http responseText.
```

It needs some work on convenience methods to make it more usable. Others may have alternative suggestions.

**Comment by Debiller777** [comment]
Woah thank you. That was very helpful. Where can I find this Http client?

ср, 7 марта 2018 г., 20:33 Blair McGlashan <notifications@github.com>:

**Comment by fxgallego** [comment]
@Debiller777  ``IWinHttpRequest`` is bundled with Dolphin. Use the find class tool.

**Comment by Debiller777** [comment]
@fxgallego Thanks you!

**Comment by blairmcg** [comment]
The HTTPClient has been removed from the standard build
