### ISSUE TITLE
Use C99 fixed-width C integer types

### ISSUE THREAD

**Issue by blairmcg** [dolphinsmalltalk/Dolphin#535]
_From @jgfoster on March 28, 2018 19:16_

The C99 standard includes definitions of several new integer types to enhance the portability of programs (per [Wikipedia](https://en.wikipedia.org/wiki/C_data_types#Fixed-width_integer_types)). I'm looking for some simple tasks where students could make a contribution. This seemed like a reasonable one so I'll create an issue to track it.

_Copied from original issue: dolphinsmalltalk/DolphinVM#163_

**Comment by jgfoster** [comment]
I'm confused by the move of this enhancement from the VM to the image. Wouldn't this require changes to the VM (or C code?).

**Comment by blairmcg** [comment]
The repos have been merged together, see #530. I did leave the PR open for several days for comments. If you have any work in progress on the VM, don't worry however, it can still be submitted via the DolphinVM repo if you want, and it can be merged in easily afterwards. Just let me know what you need to do and I'll try to help.

**Comment by jgfoster** [comment]
Excellent! Sorry I wasn't keeping up on the latest changes.

**Comment by blairmcg** [comment]
This should be completely done now.
