### ISSUE TITLE
BootDPRO: Hang on "Dolphin Community Edition Tools.pax" Error Handling

### ISSUE THREAD

**Issue by PeterMoe** [dolphinsmalltalk/Dolphin#546]
Hello,
I used the Build 7.1.1.-7-gb4a4f20c:

when I start the BootDPRO.cmd i got an Hang on "Dolphin Community Edition Tools.pax" got no Errorcodes or .ERROR File.

![error01](https://user-images.githubusercontent.com/40350726/41822637-38815096-77f3-11e8-8227-55bf62789161.jpg)

I solved the Issue on my own with searching the Issues and your sourceCode --> 
Download of [https://www.scintilla.org/wscite375.zip](https://www.scintilla.org/wscite375.zip) and extracting the "SciLexer.dll" to "\Dolphin"

I can't turn off my Firewall so i must download the file manual. Please, make a Error and a output from the WEB-Link where a user can download the file directly.
Example: **Error, Can't download "https://www.scintilla.org/wscite_Needed_Version.zip", please copy the Link and extract the SciLexer.dll to \Dolphin and restart the BootDPRO.cmd**

**Comment by blairmcg** [comment]
The download of SciLexer is an over complex solution I put in place to avoid putting a large binary in the repository when I wasn't aware of GFS. I think the best thing to do here is simply to put the DLL in the repo under GFS.

**Comment by blairmcg** [comment]
Should be fixed now. Please reopen if not.
