### ISSUE TITLE
Pac/Pax load fail with STB format error

### ISSUE THREAD

**Issue by SoundSoftware** [dolphinsmalltalk/Dolphin#571]
hi all,

i'm trying to move from v7.044 to  v7.05. when i try to load pacs which are created/loadable in v7.044 into v7.05 i get a walkback with the error "STBFiler - Input stream is an incompatable !STB format (version 4)". i have tried this with both pac and pax formats. i also tried checking the pacs/paxs into v7.044 sts. when i connect to the v7.044 repository from v7.05 all of the pacs show but when i try to load the pac i get the same error.

one thing i notice is that if i save pac as a pax AND that pax doesn't have a file named XXXXXLib with filetype of  STB it WILL load into v7.05. if the pax has the STB lib file, they won't load.

john

**Comment by blairmcg** [comment]
So it sounds like you have created packages in a recent version that you are then trying to open in an older version? If so this has come up before in #472. Maintaining forward compatibility (as opposed to backward) is a very expensive thing to do. To guarantee it would require performing test runs on old versions and loading newer assets. The matrix gets large very quickly. We don't do that, and while we don't break it deliberately, I wouldn't expect packages created on newer versions to necessarily load on down-level versions, let alone function correctly.

There are a couple of options open to you:

1. Backport the STB changes to v7.05.

1. Just drop the typelib globals out of your packages. These are really only storing options you might have put into the AX Component Wizard when generating wrappers for the components. If you did need to regenerate them, which is relatively unlikely, you could always set it up the same way again.

The 2nd approach would be much easier of course.

**Comment by SoundSoftware** [comment]
actually no. i'm trying to load a package created with an older
version into a newer version. so i expect that i s/b able load a
package created in v7.044 (older) into v7.05 (newer).

john

**Comment by blairmcg** [comment]
v7.0.5 is minor release 5 of version 7, dated 24/3/16.
v7.0.44 is minor release 44 of version 7, dated 28/7/17.

**Comment by SoundSoftware** [comment]
my bad. i assumed, without thinking, that it was .50 vs .05. 
sorry about that.
john

**Comment by blairmcg** [comment]
No need to be sorry. It is confusing, and made the more so by the presence of a v7.05 label created by mistake, although pointing at the same ref as v7.0.5. I would think you want v7.0.55.
