### ISSUE TITLE
Inspector ellipsis for more content in large object is not displayed correctly

### ISSUE THREAD

**Issue by blairmcg** [dolphinsmalltalk/Dolphin#58]
When inspecting a large object, e.g. the Win32Constants pool dictionary, the PublishedAspectInspector shows only the first 200 aspects, and a further ellipsis entry that when clicked shows the next 200, and so on. The displayed key and value for this ellipsis entry are incorrect, being an integer from the sequence 201, 401, and so on, and a value with the icon "..." (correct) and the string value "a MessageNotUnderstood" (clearly not correct).

**Comment by brunobuzzi** [comment]
It can be fixed with implementing:
KeyedAspectBatch
readFrom: anObject
	^'next ', batchSize printString, ' items'

But in the "Key" column you have you will have [batchSize] value
