### ISSUE TITLE
Presenter>>onCloseRequested never called

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#582]
If this plays a role in the Presenter lifecycle it should be documented in the method comment. As it is, I can't find a way to use it and its existence took me on a detour that wasn't very productive.

**Comment by blairmcg** [comment]
It's just an old bug that has gone unnoticed for a couple of decades (it would seem). 

`View>>wmClose:wParam:lParam:` doesn't forward to the presenter as it should:

![image](https://user-images.githubusercontent.com/15128107/42777238-533dcf78-8931-11e8-8e1d-f6bb938e6aaf.png)
