### ISSUE TITLE
Consider adding SequenceableCollection#indexOf:startingAt:

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/Dolphin#589]
This method was previously defined in the "Dialect Abstraction Layer" package, now removed, and looking at other methods similar to this seems that `#indexOf:startingAt:` is missing. (See indexOfAnyOf:, indexOfSubCollection: families)

```
indexOf: target startingAt: start
	"Answer the <integer> index of the first element of the receiver which is 
	equal to the <Object> argument, target, within the receiver. If the receiver 
	does not contain any elements equal to target, answer 0."

	^self nextIndexOf: target from: start to: self size
```

**Comment by blairmcg** [comment]
Yes, I'm surprised that is missing.
