### ISSUE TITLE
Core image doesn't build

### ISSUE THREAD

**Issue by brickviking** [dolphinsmalltalk/Dolphin#662]
Building from git.master, I've had an issue trying to build the Core images. I don't have any other version of Windows and I'm financially a LONG way from being able to upgrade it (though I do have Linux - 64-bit).

TL;DR: After saving DCORE.img7 to disk, Core cites the following MNU: MessageNotUnderstood('BootSessionManager does not understand #stashBootInfo') .

Long version:
>$ ./Dolphin7.exe DBOOT.img7 DolphinCoreProduct
Dolphin Smalltalk Boot
Copyright (c) Object Arts Ltd, 1997-2018.
Loading boot script...
Reloading BCL constants pools...
Updating ClassBuilder...
Reloading BCL class definitions...
Reloading BCL classes...
Recompiling Character class>>safeCodePoint:
Recompiling Character class>>initialize
Recompiling Character class>>utf16Value:
Recompiling Character class>>codePoint:
Deleting obsolete boot image methods...
Removing obsolete boot image method ExternalStructure class>>understoodSelectors
Removing obsolete boot image method SortedCollection class>>defaultSortAlgorithm
Loading source package 'Dolphin Registry Access' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\Registry\Dolphin Registry Access.pax
Loading source package 'Dolphin Base64' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\System\Base64\Dolphin Base64.pax
Loading source package 'Dolphin Products' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\Installation Manager\Dolphin Products.pax
Booting DolphinCoreProduct
Loading source package 'Dolphin Command-line Parser' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\Base\Dolphin Command-line Parser.pax
Loading source package 'Smalltalk Parser' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\System\Compiler\Smalltalk Parser.pax
Loading source package 'Dolphin SizeIs Fields' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\Base\Dolphin SizeIs Fields.pax
Loading source package 'Dolphin Literal Filer' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\System\Filer\Dolphin Literal Filer.pax
Loading source package 'Smalltalk Compiler' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\System\Compiler\Smalltalk Compiler.pax
Loading source package 'Dolphin Recent Menu' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\System\Recent\Dolphin Recent Menu.pax
Loading source package 'Dolphin Value Models' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Models\Value\Dolphin Value Models.pax
Loading source package 'Dolphin Type Converters' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Type Converters\Dolphin Type Converters.pax
Loading source package 'Dolphin Random Stream' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\System\Random\Dolphin Random Stream.pax
Loading source package 'Dolphin Basic Geometry' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Base\Dolphin Basic Geometry.pax
Loading source package 'Dolphin MVP Base' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Base\Dolphin MVP Base.pax
Loading source package 'Dolphin Common Dialogs' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Dialogs\Common\Dolphin Common Dialogs.pax
Loading source package 'OLE COM' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\ActiveX\COM\OLE COM.pax
Recompiling references to COMInterface (size 16)...
Loading source package 'Dolphin Common Print Dialog' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Dialogs\Common\Dolphin Common Print Dialog.pax
Loading source package 'Dolphin Text Presenter' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Presenters\Text\Dolphin Text Presenter.pax
Loading source package 'Dolphin Additional Sort Algorithms' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\Base\Dolphin Additional Sort Algorithms.pax
Loading source package 'Dolphin List Models' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Models\List\Dolphin List Models.pax
Loading source package 'Dolphin List Presenter' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Presenters\List\Dolphin List Presenter.pax
Loading source package 'Dolphin Tree Models' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Models\Tree\Dolphin Tree Models.pax
Loading source package 'Dolphin Folder Presenter' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Presenters\Folder\Dolphin Folder Presenter.pax
Loading source package 'Dolphin Common Controls' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Views\Common Controls\Dolphin Common Controls.pax
Recompiling references to NMHDR (size 12)...
Recompiling references to CCITEM (size 4)...
Recompiling references to LVITEMW (size 60)...
Loading source package 'Dolphin Choice Presenter' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Presenters\Choice\Dolphin Choice Presenter.pax
Loading source package 'Dolphin Number Presenter' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Presenters\Number\Dolphin Number Presenter.pax
Loading source package 'Dolphin Scrollbars' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Views\Scrollbars\Dolphin Scrollbars.pax
Loading source package 'Dolphin Tree Presenter' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Presenters\Tree\Dolphin Tree Presenter.pax
Loading source package 'Dolphin Boolean Presenter' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Presenters\Boolean\Dolphin Boolean Presenter.pax
Loading source package 'Dolphin Control Bars' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Views\Control Bars\Dolphin Control Bars.pax
Loading source package 'OLE Structured Storage' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\ActiveX\Structured Storage\OLE Structured Storage.pax
Loading source package 'Dolphin Image Presenter' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Presenters\Image\Dolphin Image Presenter.pax
Loading source package 'Windows Shell' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\ActiveX\Shell\Windows Shell.pax
Loading source package 'Gdiplus' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Gdiplus\Gdiplus.pax
Loading source package 'Dolphin Styled Views' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Views\Styled Views\Dolphin Styled Views.pax
Loading source package 'Dolphin Key-Value Prompter' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Presenters\Prompters\Dolphin Key-Value Prompter.pax
Loading source package 'Dolphin Text Tile Icons' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Icons\Dolphin Text Tile Icons.pax
Loading source package 'Dolphin Prompter' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Presenters\Prompters\Dolphin Prompter.pax
Loading source package 'Dolphin Collection Presenters' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Presenters\Collection\Dolphin Collection Presenters.pax
Loading source package 'Dolphin Tree List Presenter' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Presenters\Tree\Dolphin Tree List Presenter.pax
Loading source package 'Dolphin Accelerator Presenter' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Presenters\Accelerator\Dolphin Accelerator Presenter.pax
Loading source package 'Dolphin Font Presenter' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Presenters\Font\Dolphin Font Presenter.pax
Loading source package 'Dolphin MoenTree View' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Views\MoenTree\Dolphin MoenTree View.pax
Loading source package 'Dolphin Date Time Presenters' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Presenters\Date Time\Dolphin Date Time Presenters.pax
Loading source package 'Dolphin Radio Buttons' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Presenters\Radio\Dolphin Radio Buttons.pax
Loading source package 'Dolphin Date Time Controls' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Views\Date Time\Dolphin Date Time Controls.pax
Loading source package 'Dolphin Slider Control' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Views\Slider\Dolphin Slider Control.pax
Loading source package 'Dolphin Integer Prompter' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Presenters\Prompters\Dolphin Integer Prompter.pax
Loading source package 'Dolphin SpinButton Control' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Views\SpinButton\Dolphin SpinButton Control.pax
Loading source package 'Dolphin Tooltips' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Views\Tooltips\Dolphin Tooltips.pax
Loading source package 'Dolphin Card Containers' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Views\Cards\Dolphin Card Containers.pax
Loading source package 'Dolphin Color Presenter' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Presenters\Color\Dolphin Color Presenter.pax
Loading source package 'Dolphin Scintilla View' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Views\Scintilla\Dolphin Scintilla View.pax
Recompiling references to PALETTEENTRY (size 4)...
Loading source package 'Dolphin Find Dialog' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Dialogs\Find\Dolphin Find Dialog.pax
Loading source package 'Dolphin Slidey-Inney-Outey Thing' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Views\Sliding Tray\Dolphin Slidey-Inney-Outey Thing.pax
Loading source package 'Dolphin Progress Dialog' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Dialogs\Progress\Dolphin Progress Dialog.pax
Loading source package 'Dolphin Rich Text Presenter' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Presenters\Text\Dolphin Rich Text Presenter.pax
Loading source package 'Dolphin Transcript' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\IDE\Base\Dolphin Transcript.pax
Loading source package 'Debug Trace Stream' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\System\Trace\Debug Trace Stream.pax
Loading source package 'RBFormatters' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Contributions\Refactory\Refactoring Browser\Formatters\RBFormatters.pax
Loading source package 'RBParser' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Contributions\Refactory\Refactoring Browser\Parser\RBParser.pax
Loading source package 'RBEnvironments' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Contributions\Refactory\Refactoring Browser\Environments\RBEnvironments.pax
Loading source package 'RBChangeObjects' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Contributions\Refactory\Refactoring Browser\Change Objects\RBChangeObjects.pax
Loading source package 'ActiveX Automation' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\ActiveX\Automation\ActiveX Automation.pax
Recompiling references to DISPPARAMS (size 16)...
Recompiling references to VARIANT (size 16)...
Loading source package 'VBScript Regular Expressions' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\ActiveX\Components\VBScript\VBScript Regular Expressions.pax
Loading source package 'Dolphin Choice Prompter' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Presenters\Prompters\Dolphin Choice Prompter.pax
Loading source package 'Dolphin MVP (Deprecated)' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Deprecated\Dolphin MVP (Deprecated).pax
Loading source package 'Dolphin Overlapped IO' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\System\Win32\Dolphin Overlapped IO.pax
Loading source package 'Dolphin File System Watcher' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\System\Win32\Dolphin File System Watcher.pax
Loading source package 'InheritableFile' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Contributions\Burning River\InheritableFile\InheritableFile.pax
Loading source package 'KernelLibraryExtensions' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Contributions\Burning River\KernelLibraryExtensions\KernelLibraryExtensions.pax
Loading source package 'ExternalProcess' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Contributions\Burning River\ExternalProcess\ExternalProcess.pax
Loading source package 'Internal Bitmaps and Icons' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Icons\Internal Bitmaps and Icons.pax
Loading source package 'Seeing the Objects Inside' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\IDE\Base\Splash\Seeing the Objects Inside.pax
Loading source package 'OLE Font' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\ActiveX\Components\Font\OLE Font.pax
Loading source package 'ActiveX Connection Points' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\ActiveX\Connection Points\ActiveX Connection Points.pax
Loading source package 'OLE Persistence Base' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\ActiveX\Persist\OLE Persistence Base.pax
Loading source package 'ActiveX Categories' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\ActiveX\Categories\ActiveX Categories.pax
Loading source package 'ActiveX Control Hosting' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\ActiveX\OCX\ActiveX Control Hosting.pax
Loading source package 'Dolphin List Tree Presenter' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Presenters\ListTree\Dolphin List Tree Presenter.pax
Loading source package 'Development System' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\IDE\Base\Development System.pax
Recompiling references to AbstractLOGFONT (size 28)...
Recompiling references to LOGFONTW (size 92)...
Loading source package 'Dolphin SysLink Control' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Views\SysLink\Dolphin SysLink Control.pax
Loading source package 'Dolphin Announcements' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\System\Announcements\Dolphin Announcements.pax
Loading source package 'Dolphin In-place Text Editor' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Presenters\Prompters\Dolphin In-place Text Editor.pax
Loading source package 'OLE Picture' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\ActiveX\Components\Picture\OLE Picture.pax
Loading source package 'Gdiplus ImageView' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Gdiplus\Gdiplus ImageView.pax
Loading source package 'Dolphin Base Icons' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\MVP\Icons\Dolphin Base Icons.pax
Loading source package 'ActiveX Automation Development' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\IDE\Community Edition\ActiveX Automation Development.pax
Loading source package 'Dolphin Legacy Resource Framework' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\Base\Deprecated\Dolphin Legacy Resource Framework.pax
Loading source package 'Dolphin Sockets' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\Sockets\Dolphin Sockets.pax
Loading source package 'Sockets Connection' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\Sockets\Sockets Connection.pax
Loading source package 'WinInet' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\Sockets\WinInet.pax
Loading source package 'ADODB' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\ActiveX\Components\ADO\ADODB.pax
Recompiling references to TLIBATTR (size 32)...
Loading source package 'CDO' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\ActiveX\Components\CDO\CDO.pax
Loading source package 'US ExternalProcess Extensions' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Contributions\Udo Schneider\US ExternalProcess Extensions.pax
Loading source package 'XML DOM' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\ActiveX\Components\XML DOM\XML DOM.pax
Loading source package 'ActiveX Scripting' from: C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\Core\Object Arts\Dolphin\ActiveX\Components\Scripting\ActiveX Scripting.pax
Uninstalling package 'Gdiplus ImageView'
Uninstalling package 'ActiveX Automation Development'
Uninstalling package 'Development System'
Uninstalling package 'Dolphin File System Watcher'
Uninstalling package 'Dolphin Overlapped IO'
Saving booted image to C:\Users\viking\Documents\Dolphin Smalltalk 7\src\Dolphin\DCORE.img7
Error: UndefinedObject>>doIt at line 1: undeclared 'DevelopmentSessionManager'
----------------------------------------Unhandled exception - a MessageNotUnderstood('BootSessionManager does not understand #stashBootInfo')
==
BootSessionManager(Object)>>doesNotUnderstand:
UndefinedObject>>{unbound}doIt
Compiler class>>evaluate:for:evaluationPools:logged:ifFail:
Compiler class>>evaluate:for:evaluationPools:logged:
Compiler class>>evaluate:for:logged:
[] in ChunkSourceFiler>>{unbound}fileIn
ExceptionHandler(ExceptionHandlerAbstract)>>{unbound}markAndTry
[] in ExceptionHandler(ExceptionHandlerAbstract)>>{unbound}try:
BlockClosure>>{unbound}ifCurtailed:
BlockClosure>>{unbound}ensure:
ExceptionHandler(ExceptionHandlerAbstract)>>{unbound}try:
BlockClosure>>{unbound}on:do:
ChunkSourceFiler>>{unbound}fileIn
SourceManager>>{unbound}fileInFrom:normalizeLineEndings:
[] in SourceManager>>{unbound}fileIn:normalizeLineEndings:
BlockClosure>>{unbound}ifCurtailed:
BlockClosure>>{unbound}ensure:
SourceManager>>{unbound}fileIn:normalizeLineEndings:
SourceManager>>{unbound}fileIn:
BootSessionManager>>{unbound}main
BootSessionManager(SessionManager)>>{unbound}mainLoopStarted
[] in BootSessionManager(SessionManager)>>{unbound}forkMain
InputState>>{unbound}loopWhile:
InputState>>{unbound}mainLoop
[] in InputState>>{unbound}forkMain
ExceptionHandler(ExceptionHandlerAbstract)>>{unbound}markAndTry
[] in ExceptionHandler(ExceptionHandlerAbstract)>>{unbound}try:
BlockClosure>>{unbound}ifCurtailed:
BlockClosure>>{unbound}ensure:
ExceptionHandler(ExceptionHandlerAbstract)>>{unbound}try:
BlockClosure>>{unbound}on:do:
[] in BlockClosure>>{unbound}newProcess:

Regards, BrickViking (a.k.a. DrSmokey)

**Comment by blairmcg** [comment]
The Core configuration is obsolete. It used to be a cut down free version when Dolphin Pro was a commercial product. I don’t think there is good reason to use it any longer, and maintaining it is extra cost for no obvious value. I’ll remove it to avoid the confusion.

**Comment by brickviking** [comment]
Okay, fair enough. That means BootCore.cmd and presumably BootAll.cmd would go, and people would just have BootDPRO.cmd (and associated changes).

I'm also running into "interesting" build problems trying to build the DPRO image under wine using the available downloaded VM on 64-bit Fedora; it's getting so far, but croaking somewhere after compiling some methods. Do you want me to bother posting the attempt here as a PR? It's getting a lot further than building under Vista does now because of the other bcrypt issue.

**Comment by brickviking** [comment]
On Fedora 27 (64-bit), I've been able to create images both for 7.0.57.2 and for 7.1.3. Though I can then boot a 7.0.57 image under Wine using the supplied VM, I still can't do the same for 7.1.3, which cites an fpException in the ProcessorScheduler>>vmi:list:no:with: method, but only under Wine. I'll post this as a separate issue once I can find a fix, as that's what you've indicated for a preference.
