### ISSUE TITLE
Missing help file for ChunkBrowser window

### ISSUE THREAD

**Issue by brickviking** [dolphinsmalltalk/Dolphin#687]
Two bugs, this time very closely related, neither of them killers.

### First (and main) bug

Selecting Help in the ChunkBrowser window coughs up a Debugger with the following response:
>4:34:08 p.m., Friday, 9 November 2018: 'The system cannot find the file specified. (16r2: The system cannot find the file specified.)' (the file was c:\Users\viking\Documents\Dolphin Smalltalk 7\Core\Contributions\IDB\Documentation\idbchunkbrowser.html)
ShellLibrary(ExternalLibrary)>>systemError
ShellLibrary>>shellOpen:directory:parameters:
ShellLibrary>>shellOpen:directory:
ShellLibrary>>shellOpen:
ChunkBrowser class(IdbShell class)>>idbHelp:
ChunkBrowser(IdbShell)>>idbHelp:
ChunkBrowser>>idbHelp
Symbol>>forwardTo:
CommandDescription>>performAgainst:
[] in Command>>value
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
Command>>value
ShellView>>performCommand:
ChunkBrowser(Shell)>>performCommand:
CommandQuery>>perform
DelegatingCommandPolicy(CommandPolicy)>>route:
[] in ShellView(View)>>onCommand:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
Cursor>>showWhile:
ShellView(View)>>onCommand:
ShellView(View)>>wmCommand:wParam:lParam:
ShellView(View)>>dispatchMessage:wParam:lParam:
[] in InputState>>wndProc:message:wParam:lParam: cookie:
BlockClosure>>ifCurtailed:
InputState>>wndProc:message:wParam:lParam: cookie:
InputState>>pumpMessage:
InputState>>loopWhile:
InputState>>mainLoop
[] in InputState>>forkMain
ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry
[] in ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>on:do:
[] in BlockClosure>>newProcess:

Sorry about the smilies in the above text, that wasn't intended.

To reproduce: fire up Dolphin Professional, click "Additional Tools", select (and execute) Chunk Browser. When the window appears, click "Help" menu, then click the Help entry (first one). The file being looked for is called idbchunkbrowser.html, the closest match I could find (which was practically empty except for a title) is chunkbrowser.html in that same directory, in this case, buried down in the Dolphin src directory.

### Second "bug"

I'm not sure whether any of the documentation for IDB actually exists as anything BUT a couple of words on each web page, but if there is any, it'd be nice to have it working, or point the Help menu entry to somewhere else.

Regards, BrickViking (a.k.a. DrSmokey)

**Comment by blairmcg** [comment]
I've looked around for this, but the only help files I can find are empty except for a title. I'm not sure whether Ian ever wrote any text, but these tools were written before 2000 so it is almost certainly lost if it ever existed.
