### ISSUE TITLE
[Wine] Division by zero error in TextTileIcon>>drawOnGraphics:at:extent:

### ISSUE THREAD

**Issue by brickviking** [dolphinsmalltalk/Dolphin#689]
I'm a little stuck here. Actually, I'm a lot stuck. I've tried running 7.1.3's VM with a generated DPRO image from master, with the error "Division by zero of 20.0". The same issue appears with the 7.1.3 DPRO image too, though a different figure results (Division by Zero of 38.0).

I don't get any windows (aside from splash) appearing except for the usual Debug/Resume/Terminate/Copy prompter, and I can't rebuild the VM to include debugging support, so I'm unable to even pose an idea of what's wrong, nor bring up any source browsing window or even an Inspector.

I took a look at the relevant function (Core/Object Arts/Dolphin/MVP/Icons/TextTileIcon.cls:184), and I can only surmise that in the calculation for scale, textExtent x or textExtent y evaluates to 0 for some strange reason, meaning that the scale calculation is off and causing the fpException in /.

Anyhow, what information I did manage to grab from the aforementioned window is here:

>9:29:16 p.m., Thursday, 29 November 2018: 'Division by zero of 20.0'
ProcessorScheduler>>fpException:
[] in ProcessorScheduler>>vmi:list:no:with:
BlockClosure>>ifCurtailed:
ProcessorScheduler>>vmi:list:no:with:
Float>>/
TextTileIcon>>drawOnGraphics:at:extent:
TextTileIcon>>bitmapWithExtent:
TextTileIcon>>addToImageList: mask:
[] in ImageManager>>basicAddImage:extent:maskcolor:
LookupTable>>do:
IconImageManager(ImageManager)>>basicAddImage:extent:maskcolor:
IconImageManager(ImageManager)>>addImage:extent:maskcolor:
IconImageManager(ImageManager)>>addImage:maskcolor:
IconImageManager(ImageManager)>>addImage:
[] in IconImageManager(ImageManager)>>indexOfImage:
LookupTable>>at:ifAbsent:
IconImageManager(ImageManager)>>indexOfImage:
TextTileIcon>>imageIndex
TextTileIcon>>asAlphaBitmap:
[] in IconImageManager>>bitmapForIcon:extent:
LookupTable(Dictionary)>>at:ifAbsentPut:
IconImageManager>>bitmapForIcon:extent:
IconImageManager>>menuBitmapForIcon:
TextTileIcon>>asMenuBitmap
MENUITEMINFOW>>setImage:
MENUITEMINFOW>>commandMenuItem:
CommandMenuItem>>populateItemInfo:
CommandMenuItem(MenuItem)>>insertIntoMenu:at:info:
[] in Menu>>basicRealize
Array(SequenceableCollection)>>uncheckedFrom:to:keysAndValuesDo:
Array(SequenceableCollection)>>keysAndValuesDo:
Menu>>basicRealize
Menu(GraphicsTool)>>realize
Menu(GraphicsTool)>>handle
Menu>>insertIntoMenu:at:info:
[] in MenuBar(Menu)>>basicRealize
Array(SequenceableCollection)>>uncheckedFrom:to:keysAndValuesDo:
Array(SequenceableCollection)>>keysAndValuesDo:
MenuBar(Menu)>>basicRealize
MenuBar(GraphicsTool)>>realize
MenuBar(GraphicsTool)>>handle
MenuBar(GraphicsTool)>>asParameter
ShellView>>basicMenu:
ShellView>>updateMenuBar
MessageSend(MessageSendAbstract)>>value
[] in MessageSequenceAbstract>>value
OrderedCollection>>do:
MessageSequence>>messagesDo:
MessageSequence(MessageSequenceAbstract)>>value
ShellView(View)>>state:

Any further ideas about what to do with this? Sorry I can't take it any further than this.

Regards, BrickViking (a.k.a. DrSmokey)

**Comment by blairmcg** [comment]
Two things you could try:
1. Use winetricks to install the native gdiplus.dll, as there is probably some incompatibility in the wine version. This is easiest, but will just sidestep the issue in/with wine.
2. Edit the Smalltalk code manually to clamp the extents (or whatever intermediate value might be causing div by zero) to a minimum value greater than zero (eg 1). You can reboot to do this or put a chunk format method definition in a prestart.st file in the startup folder. This approach would allow for further investigation, but there would be cosmetic issues with the text tile icons.

**Comment by brickviking** [comment]
I went for the first option as I don't really have the understanding to create the second. Your suggestion was great, and has resulted in me being able to display a working 7.1.3-master image. I have other issues now, but I'll post the next wine-related issue separately (#690) to keep it out of this thread. 

Thanks again for your help.

**Comment by blairmcg** [comment]
Closing this as it is an external issue with Wine, as installing the actual gdiplus DLL demonstrates. I don't think we want to modify the code base to work around issues in Wine for which there are other solutions.
