### ISSUE TITLE
[Wine] errors on starting browsers.

### ISSUE THREAD

**Issue by brickviking** [dolphinsmalltalk/Dolphin#690]
I've struck some errors under wine while trying to start various browsers from the System Folder. If I double-click on a Class Browser, I get two debugger windows, one for "UndefinedObject does not understand #*" and the second one (once I click Resume on the first) for "DevelopmentSessionManager does not understand #truncate". I then get another pair of these.

>6:13:37 p.m., Friday, 30 November 2018: 'UndefinedObject does not understand #*'
Object>>doesNotUnderstand: 

The failedMessage is:  Message selector: #* arguments: #((5/4)) 
The relevant line from resolutionScaledBy: reads
     indentSeparation := (indentSeparation * scale x) truncated.
      (scale: (5/4)@(5/4), indentSeparation: nil )

Rest of debugger dump follows:
>TreeView>>resolutionScaledBy:
TreeView(View)>>restorePlacement:resolution:
TreeView(STBViewProxy)>>restoreView
[] in STBViewProxy>>restoreView
Array(ArrayedCollection)>>do:
ContainerView(STBViewProxy)>>restoreView
ContainerView(STBViewProxy)>>restoreTopView
[] in ContainerView(STBViewProxy)>>stbFixup:at:
[] in STBInFiler>>evaluateDeferredActions
OrderedCollection>>do:
STLInFiler(STBInFiler)>>evaluateDeferredActions
STLInFiler(STBInFiler)>>next
ResourceIdentifier>>loadWithContext:forEdit:
ResourceIdentifier>>loadWithContext:
ReferenceView>>loadReferee
ReferenceView>>referee
ReferenceView>>createDelegate
ReferenceView(AbstractDelegatingView)>>onViewCreated
ReferenceView(View)>>createAt:extent:
MessageSend(MessageSendAbstract)>>value
[] in MessageSequenceAbstract>>value
OrderedCollection>>do:
MessageSequence>>messagesDo:
MessageSequence(MessageSequenceAbstract)>>value
ReferenceView(View)>>state:
ReferenceView(STBViewProxy)>>restoreView
[] in STBViewProxy>>restoreView
Array(ArrayedCollection)>>do:
ContainerView(STBViewProxy)>>restoreView
[] in STBViewProxy>>restoreView
Array(ArrayedCollection)>>do:
ContainerView(STBViewProxy)>>restoreView
[] in STBViewProxy>>restoreView
Array(ArrayedCollection)>>do:
ShellView(STBViewProxy)>>restoreView
ShellView(STBViewProxy)>>restoreTopView
[] in ShellView(STBViewProxy)>>stbFixup:at:
[] in STBInFiler>>evaluateDeferredActions
OrderedCollection>>do:
STLInFiler(STBInFiler)>>evaluateDeferredActions
STLInFiler(STBInFiler)>>next
ResourceIdentifier>>loadWithContext:forEdit:
ResourceIdentifier>>loadWithContext:
ClassBrowserShell class(Presenter class)>>loadViewResource:inContext:
ClassBrowserShell(Shell)>>createView:
ClassBrowserShell class(Shell class)>>create:
ClassBrowserShell class(Presenter class)>>create
ClassBrowserShell class(Presenter class)>>show
ClassBrowserShell class(SmalltalkToolShell class)>>show

I can proceed by clicking "Resume" but something smells funny, as the number of debug windows change depending on what I click on. The second debugger window pops this up:
>10:38:17 p.m., Friday, 30 November 2018: 'DevelopmentSessionManager does not understand #truncated'
DevelopmentSessionManager(Object)>>doesNotUnderstand:

The failedMessage in this case is: Message selector: #truncated
There's plenty of other fields in this, but that's the one that raises the debugger.
The rest of the debugger output:

>TreeView>>resolutionScaledBy:
TreeView(View)>>restorePlacement:resolution:
TreeView(STBViewProxy)>>restoreView
[] in STBViewProxy>>restoreView
Array(ArrayedCollection)>>do:
ContainerView(STBViewProxy)>>restoreView
ContainerView(STBViewProxy)>>restoreTopView
[] in ContainerView(STBViewProxy)>>stbFixup:at:
[] in STBInFiler>>evaluateDeferredActions
OrderedCollection>>do:
STLInFiler(STBInFiler)>>evaluateDeferredActions
STLInFiler(STBInFiler)>>next
ResourceIdentifier>>loadWithContext:forEdit:
ResourceIdentifier>>loadWithContext:
ReferenceView>>loadReferee
ReferenceView>>referee
ReferenceView>>createDelegate
ReferenceView(AbstractDelegatingView)>>onViewCreated
ReferenceView(View)>>createAt:extent:
MessageSend(MessageSendAbstract)>>value
[] in MessageSequenceAbstract>>value
OrderedCollection>>do:
MessageSequence>>messagesDo:
MessageSequence(MessageSequenceAbstract)>>value
ReferenceView(View)>>state:
ReferenceView(STBViewProxy)>>restoreView
[] in STBViewProxy>>restoreView
Array(ArrayedCollection)>>do:
ContainerView(STBViewProxy)>>restoreView
[] in STBViewProxy>>restoreView
Array(ArrayedCollection)>>do:
ContainerView(STBViewProxy)>>restoreView
[] in STBViewProxy>>restoreView
Array(ArrayedCollection)>>do:
ShellView(STBViewProxy)>>restoreView
ShellView(STBViewProxy)>>restoreTopView
[] in ShellView(STBViewProxy)>>stbFixup:at:
[] in STBInFiler>>evaluateDeferredActions
OrderedCollection>>do:
STLInFiler(STBInFiler)>>evaluateDeferredActions
STLInFiler(STBInFiler)>>next
ResourceIdentifier>>loadWithContext:forEdit:
ResourceIdentifier>>loadWithContext:
ClassBrowserShell class(Presenter class)>>loadViewResource:inContext:
ClassBrowserShell(Shell)>>createView:
ClassBrowserShell class(Shell class)>>create:
ClassBrowserShell class(Presenter class)>>create
ClassBrowserShell class(Presenter class)>>show
ClassBrowserShell class(SmalltalkToolShell class)>>show

For example, File Browser and Protocol Browser turn up two debugger windows, but Class Browser, Executable Browser and Profile Browser turn up four debug windows, Package Browser and System Browser both turn up six. (What the heck are those debug things called, anyhow?) In each case, scale is (5/4)@(5/4) and failedMessage is either "Message selector: #* arguments: #((5/4)) " or "Message selector: #truncated".

Any ideas what I need to look at in these cases? I certainly don't appear to get the same problem under Vista.

Regards, BrickViking (a.k.a. DrSmokey)

**Comment by blairmcg** [comment]
I think this is a straightforward bug when the resolution is changed and the TreeView indentSeparation is nil (which is an expected case where no explicit separation is specified to indicate the default node indentation should be used). I'll push a simple fix for it so you can try it.

Resuming a walkback will only work in certain cases where a knock-on-error will not occur - it depends what happens next, whether a sensible return value is expected, etc. In many cases it is possible to recover by going into the debugger and returning a specific value from the MNU that is of the type the caller is expecting to get back. Also for errors in the views you might get multiple occurrences of the same error because there are multiple types of the same control. I think there are at least four tree views in a System Browser, for example.

**Comment by brickviking** [comment]
I patched it with your commit in-image, it seems to get rid of  the error dialogs. Thanks for that.
