### ISSUE TITLE
ClassLocator class' ImportedClasses is never initialized

### ISSUE THREAD

**Issue by Sergiomdf** [dolphinsmalltalk/Dolphin#698]
The changes in 282be5fd22a0040ef29f8678ab9ea0dc8b78a62a removed all initializations of the class variable 'ImportedClasses' of ClassLocator. So, an 'UndefinedObject does not understand #lookup:' error is signalled when trying to read an STBClassProxy.

**Steps to reproduce:**
1. Open a clean Dolphin image.
1. Create a new class, MyClass
1. Export it to a binary file by evaluating this code:
``MyClass binaryStoreOn: (FileStream write: 'MyClass.bin' text: false).``
1. Close the image, without saving the changes.
1. Open a clean Dolphin image.
1. Try to import the exported class, evaluating this code:
``Class binaryReadFrom: (FileStream read: 'MyClass.bin' text: false).``

**Obtained result:** An 'UndefinedObject does not understand #lookup:' error is signalled.
**Expected result:** the class MyClass is imported from the binary file and available in the image.

**Comment by blairmcg** [comment]
We can fix the error, but I'm afraid your expected result is not what will happen. STB has never supported saving/restoring individual classes like that, only as part of binary packages. See the Web applet stuff, which has never been included amongst the loaded content of the Dolphin 7 image, and so almost certainly doesn't work any more.
