### ISSUE TITLE
Strange behaviour: IdentityDictionary and LargeIntegers

### ISSUE THREAD

**Issue by JatKedvs** [dolphinsmalltalk/Dolphin#714]
There is a strange behaviour when using IdentityDictionary with LargeIntegers

`| test |
Notification signal: '-----------------------------------------------'.

test := IdentityDictionary new.

test at: (Integer fromString: '400327300') put: 'Test 1'.
Notification signal: (test at: (Integer fromString: '400327300') ifAbsent: ['400327300 Test 1 not']),' found'.

test at: (Integer fromString: '4003273000001') put: 'Test 2'.
Notification signal: (test at: (Integer fromString: '4003273000001') ifAbsent: ['4003273000001 Test 2 not']),' found'.

test do: [:each | Notification signal: (each)].`

The output shows the following:

> -----------------------------------------------
Test 1 found
4003273000001 Test 2 not found
Test 1
Test 2

**Comment by blairmcg** [comment]
This is as expected. Two LargeIntegers of equal value need not be identical as they can be separate objects. Each time a new LargeInteger is created, you will get a separate object allocated form the heap. IdentityDictionaries should only be used with objects guaranteed to have a single instance for each representable value (e.g. instances of SmallInteger, Symbol, Object, or classes). They should not be used for objects for which there may be more than one instance representing the same value (e.g. LargeInteger, String, Float, or Character).
