### ISSUE TITLE
Add support for easily creating anonymous classes

### ISSUE THREAD

**Issue by blairmcg** [dolphinsmalltalk/Dolphin#717]

**Comment by jgfoster** [comment]
This looks intriguing. I don't see any use in the image (yet). Would you share a few words on the motivation or possible uses? Thanks!

**Comment by blairmcg** [comment]
It was motivated initially by porting STON, which has tests using this capability. I haven't published that yet though as I got sidetracked into something else the STON tests touch on.
Tests are an important use case since sometimes it is useful to dynamically create objects with refined behaviour to make it easier to test things in isolation. Classes can be generated anyway (and some of the existing tests do this), but anonymous classes are much lighter weight and have no lasting impact on the system. They don't trigger any system update events and will just disappear when unreferenced. They can also be used easily to implement instance specific behaviour by creating an anonymous subclass of an object's existing class, and then changing the class of the object to that anonymous class. You can then compile in methods.
There are other potential uses such as intercession, e.g. instance specific breakpoints. Or to compile code for temporary use that should be garbage collected when no longer required, but which might require more than just the odd unbound method.

**Comment by fxgallego** [comment]
@blairmcg I've noted that compilation of methods in Anonymous classes via `compile:` is writing to the changes file. Is there some way to compile avoiding this? I have a useful use case for this but it would compile some large methods and I wouldn't like flood my changes with garbage.

**Comment by blairmcg** [comment]
Yes, because you might need the source for debugging, etc. It can be avoided if you step down to the raw Compiler methods. If you start with a copy of Behavior>>basicCompile:flags:, you can just strip it down to what you need to compile the method and add it to the method dictionary.
