### ISSUE TITLE
Ability to compare Smalltalk formatted code with Dolphin DifferencesPresenter

### ISSUE THREAD

**Issue by brunobuzzi** [dolphinsmalltalk/Dolphin#726]
Right now you can compare code as plain text. It will be very useful the ability to compare Smalltalk formatted code.
A class like DiffsSmalltalkScintillaStyler should be create in ScintillaStyler hierarchy.

**Comment by blairmcg** [comment]
I think it would probably be better to dispense with the diffs styler altogether and use Scintilla indicators instead. This is the same as the way that brace highlighting and selection matching is done, and would allowing diff highlighting to be independent of the syntax colouring.

**Comment by brunobuzzi** [comment]
For now i have the following:
![image](https://user-images.githubusercontent.com/4719282/56476931-ee17d000-6475-11e9-9fa5-1327a1ec0a06.png)
StDifferencesPresenter as subclass of DifferencesPresenter.
In StDifferencesPresenter there are two **TextStyles**, one is the code style for normal Smalltalk code and the other is ofr Diff Smalltalk code. Both are the same but Diff has `backcolor:` with a value. Also the name of ScintillaTextStyle add Diff:
```
((ScintillaTextStyle name: #illegalDiff)
					id: 100;
					description: 'Illegal characters, e.g. £';
					forecolor: Color red;
					backcolor: Color yellow;
					isBold: true;
					yourself)
```
So different tokens can have different backcolor. The implementation is very simple and a little hackish (the Diff added to scintilla tokens).
DiffSmalltalkMethodStyler (subclass of SmalltalkMethodStyler) re implement:
`colourTokens:startingAt:`
And new method added `applyStyle:from:to:`
```
applyStyle: aSymbol from: start to: end 
	"The receiver apply style named <aSymbol> from token start <start> to token end <end>.
	If the token is contained in <diffs> collection then the style applied is <aSymbol> + <Diff>"
	| style diffSymbol |

	(end - start) < 1 ifTrue: [^self].
	(arrayDepth > 0 or: [aSymbol == #literalArray]) ifTrue: [view setIndicator: self literalArrayIndicatorId from: view stylingPosition length: (end - start)].
	diffSymbol :=  (diffs anySatisfy: [:interval | interval includes: start]) 
				ifTrue: [(aSymbol , 'Diff') asSymbol] 
				ifFalse: [aSymbol].
	style := view styleNamed: diffSymbol.
	view styleNext: (end - start) mask: (style ifNil: [0] ifNotNil: [style id]).
```

**Comment by blairmcg** [comment]
Hmmm, I think I was responsible for the original design of using a styler to do the diff highlighting, but this does rather demonstrate it was the wrong approach. It turns out to be much simpler with indicators, and the diff specific styler can be removed altogether. See https://github.com/dolphinsmalltalk/Dolphin/tree/blairmcg/indicatorDiffs
