### ISSUE TITLE
ProcessTest>>testLargeAddress is unreliable in CI builds

### ISSUE THREAD

**Issue by blairmcg** [dolphinsmalltalk/Dolphin#734]
ProcessTest>>testLargeAddress fails intermittently (perhaps 1 in 10) in appveyor builds, e.g

https://ci.appveyor.com/project/dolphinsmalltalk/dolphin-db22v/builds/23971063

**Comment by blairmcg** [comment]
This is now skipped. I'll leave this open to remind me to look at it again sometime.

**Comment by jgfoster** [comment]
In my environment I get five errors in ProcessTest. Trying to run testLargeAddress by itself pops up with many error messages and leave the image essentially locked up. I'm happy to investigate further if you have any advice.

**Comment by blairmcg** [comment]
This has been stable in the CI since, and I was able to run it 1000 times in a loop without issue just now, so it must be related to the host environment. It does deliberately allocate a large amount of memory in order to force Process stacks to be created over the 2Gb boundary. I would expect it to fail on true 32-bit Windows (as opposed to 64-bit Windows hosting a 32-bit app, which allows the app to access the full 4Gb address space). What are you running it on?

**Comment by jgfoster** [comment]
I'm on 32-bit Windows. It is a VM inside the latest Macintosh and I keep it mostly to run Dolphin so haven't seen the need to upgrade. Given the 64-bit requirement, I'll ignore these test failures. Thanks for the explanation.

**Comment by blairmcg** [comment]
James, I'm sure we can detect that we are running on 32-bit Windows and skip the offending tests automatically. Aside from `testLargeAddress`, which are failing for you?

**Comment by jgfoster** [comment]
With the latest code (30b81d13b1a3dd83765b7186b74a81e1cc752977) I see the following in RegressionTests.xml: <testsuites name="RegressionTests" tests="5574" errors="0" failures="0" skipped="22" time="185.802656">. So it appears that `testLargeAddress` was the only one (or was having an impact on the others as a side-effect. Thank you very much!
