### ISSUE TITLE
Last BootDPRO Build does not work

### ISSUE THREAD

**Issue by brunobuzzi** [dolphinsmalltalk/Dolphin#771]
**Describe the bug**
Executing BootDPRO.cmd fail to generate a Dolphin image.

**To Reproduce**
1. Clone Dolphin repo
2. Fetch VM
3. Execute BootDPRO.cmd

**Expected behavior**
Create a clean Dolphin image

**Screenshots**

**Please complete the following information):**
 - OS: Windows 8
 - Dolphi 7.1.4
**Additional context**
Loading source package 'Development System' from: C:\Users\Usuario\Documents\Git
Hub\Dolphin\Core\Object Arts\Dolphin\IDE\Base\Development System.pax
Recompiling references to AbstractLOGFONT (size 28)...
Recompiling references to LOGFONTW (size 92)...
----------------------------------------Unhandled exception - a MessageNotUnders
tood('Array does not understand #negated')

Array(Object)>>doesNotUnderstand:
Font>>pointSize:
Font class>>name:pointSize:
SmalltalkWorkspace class>>initialize
SmalltalkWorkspace class(Class)>>initializeAfterLoad
[] in Package>>initializeClasses
Array(ArrayedCollection)>>do:
Package>>initializeClasses
Package>>initializeGlobals
[] in Package>>loadPAX
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
Package>>loadPAX
Package>>load
PackageManager>>basicInstall:
[] in PackageManager>>install:
BlockClosure>>ifCurtailed:
[] in PackageManager>>install:
OrderedCollection>>do:
[] in PackageManager>>install:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
PackageManager>>install:
[] in DolphinProduct>>basicLoad
ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry
[] in ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>on:do:
[] in DolphinProduct>>basicLoad
PluggableLookupTable(LookupTable)>>at:ifAbsent:
PackageManager>>packageNamed:ifNone:
[] in DolphinProduct>>basicLoad
OrderedCollection>>do:
DolphinProfessional(DolphinProduct)>>basicLoad
DolphinProfessional(DolphinProduct)>>loadShrinkAndCompress
DolphinProfessional(DolphinProduct)>>boot
DolphinProfessional class(DolphinProduct class)>>boot
[] in UndefinedObject>>{unbound}doIt
ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry
[] in ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>on:do:
UndefinedObject>>{unbound}doIt
Compiler class>>evaluate:for:evaluationPools:logged:ifFail:
Compiler class>>evaluate:for:evaluationPools:logged:
Compiler class>>evaluate:for:logged:
[] in ChunkSourceFiler>>{unbound}fileIn
ExceptionHandler(ExceptionHandlerAbstract)>>{unbound}markAndTry
[] in ExceptionHandler(ExceptionHandlerAbstract)>>{unbound}try:
BlockClosure>>{unbound}ifCurtailed:
BlockClosure>>{unbound}ensure:
ExceptionHandler(ExceptionHandlerAbstract)>>{unbound}try:
BlockClosure>>{unbound}on:do:
ChunkSourceFiler>>{unbound}fileIn
SourceManager>>{unbound}fileInFrom:normalizeLineEndings:
[] in SourceManager>>{unbound}fileIn:normalizeLineEndings:
BlockClosure>>{unbound}ifCurtailed:
BlockClosure>>{unbound}ensure:
SourceManager>>{unbound}fileIn:normalizeLineEndings:
SourceManager>>{unbound}fileIn:
BootSessionManager>>{unbound}main
BootSessionManager(SessionManager)>>{unbound}mainLoopStarted
[] in BootSessionManager(SessionManager)>>{unbound}forkMain
InputState>>{unbound}loopWhile:
InputState>>{unbound}mainLoop
[] in InputState>>{unbound}forkMain
ExceptionHandler(ExceptionHandlerAbstract)>>{unbound}markAndTry
[] in ExceptionHandler(ExceptionHandlerAbstract)>>{unbound}try:
BlockClosure>>{unbound}ifCurtailed:
BlockClosure>>{unbound}ensure:
ExceptionHandler(ExceptionHandlerAbstract)>>{unbound}try:
BlockClosure>>{unbound}on:do:
[] in BlockClosure>>{unbound}newProcess:
----------------------------------------

Shutting down boot session
Boot failed, Code=-1

**Comment by blairmcg** [comment]
If you are fetching VM 7.1.4, then your repo is out of date (see https://github.com/dolphinsmalltalk/Dolphin/tags). Have you fetched the tags?

**Comment by brunobuzzi** [comment]
Thanks Blair,
`FetchVM.cmd v7.1.6` fix the problem FetchVM.cmd without argument fail. **This can be closed !**
It is explained here:
https://github.com/dolphinsmalltalk/Dolphin/issues/757#issuecomment-487681393

**Comment by blairmcg** [comment]
If you have the tags locally and have checked out (or from) master, then FetchVM will download the latest tagged version - you do not need to specify it. Remember that if you are working from a fork, then if you update it by fetching and pushing to it, git does not push tags by default. Depending on how you cloned/ fetched, you may not get them either. Try running `git describe` to see what you have. From the current state of master it should say `v7.1.6-4-g4dc63497`
