### ISSUE TITLE
Include Database Connections tests in the CI build

### ISSUE THREAD

**Issue by blairmcg** [dolphinsmalltalk/Dolphin#780]
The Database Connection tests are limited, and not even loaded with the regular tests, let alone executed. They don't have much value if they are not run, so we should add them in to the build, especially as @rko281 has done some work to improve them as part of fixing #768 and #778 recently.

This will mean including a Northwind.mdb in the repository, but I think that will be fine if added to Git LFS. We'll also need to ensure the necessary pre-requisites are available on the build machine, and degrade gracefully if not.

**Comment by fxgallego** [comment]
I'm looking at this.
The tests run well with some minor adjustments.
I'd like to run the tests against Access and SQL Server.

I have a question about this test:
```
testViewsQuery
	| views |
	views := connection views.
	self 
		assert: (views noDifference: (self isAccessDB 
						ifTrue: 
							[#('Alphabetical List of Products' 'Category Sales for 1997' 'Current Product List' 'Customers and Suppliers by City' 'Employee Sales by Country' 'Invoices' 'Invoices Filter' 'Order Details Extended' 'Order Subtotals' 'Orders Qry' 'Product Sales for 1997' 'Products Above Average Price' 'Products by Category' 'Quarterly Orders' 'Quarterly Orders by Product' 'Sales by Category' 'Sales by Year' 'Ten Most Expensive Products')]
						ifFalse: 
							[#('Alphabetical list of products' 'Category Sales for 1997' 'Current Product List' 'Customer and Suppliers by City' 'Invoices' 'Order Details Extended' 'Order Subtotals' 'Orders Qry' 'Product Sales for 1997' 'Products Above Average Price' 'Products by Category' 'Quarterly Orders' 'Sales by Category' 'Sales Totals by Amount' 'Summary of Sales by Quarter' 'Summary of Sales by Year' 'sysconstraints' 'syssegments')]))
```
I've got `Northwind.mdb` but with other contents, for example: 'Category Sales for 1995', causing this test to fail. Do you have at hand the same database used in this tests? I can't find it. Anyway it's almost the same so I only have to repair this test.

**Comment by blairmcg** [comment]
I've added as an LFS object in the original location referred to by the tests (which is in the package folder).
All the tests passed when I ran them against it.

**Comment by fxgallego** [comment]
I've got a fail with the trace file due to permissions: can't write to C:\ . I changed it to a temp file and it worked. Also several tests are failing on "my machine", I'm sure most of them because I'm using a Spanish Windows. I'll investigate each one.
![image](https://user-images.githubusercontent.com/2080171/83950630-a3d0ea00-a802-11ea-9d90-2a20de86958c.png)

**Comment by blairmcg** [comment]
Yes, looks like you are right for most cases, based on the types of test that are failing.

**Comment by blairmcg** [comment]
I can certainly make TypeConverterTest>>testInvalidDurationFormat fail just by changing the default Locale to one in which commas are used for decimal points instead of periods. WindowsLocaleTest>>testDisplayOn is interesting as that one does actually test in a variety of Locales, so it will be interestng to see what you find there.

**Comment by blairmcg** [comment]
I'll push what should be fixes for most of them (those that reproduce easily on English Windows if I just change the default user Locale in Dolphin while they run) into my current PR.

**Comment by fxgallego** [comment]
Ok I'll check again after

**Comment by fxgallego** [comment]
Now there are only 2 left, results are in windows caption:
CanvasTest>>testOutlineTextMetrics
![image](https://user-images.githubusercontent.com/2080171/83952860-65432b80-a812-11ea-9a06-c93bf7368eb0.png)

WindowsLocaleTest>>testDisplayFloatOn (my locale uses $, as decimal separator and $. for thousands)
![image](https://user-images.githubusercontent.com/2080171/83952890-9e7b9b80-a812-11ea-95f0-0f4fc9f23eb2.png)

**Comment by blairmcg** [comment]
The first one I can understand. Obviously the font style name is going to be localised.

The 2nd is odd. This test is testing the printing of numbers with different regional formats. It's printing it with fr-FR, so it shouldn't matter what the system locale is. What is odd about it is that it works at al, since the decimal separator should always be ',' in this part of the test. If you look further up you'll see that it has already tested cases where the separator is ','. Hmmm.

**Comment by blairmcg** [comment]
Ah, 1024 doesn't exist, so it is picking up the default.

**Comment by fxgallego** [comment]
Yes, that's it. It returns AR for me

**Comment by fxgallego** [comment]
I'm running the tests against SQL Server 2017. I decided to use a TestResource for the database, creating it from scratch in `setUp` and dropping it in `tearDown` once for all tests.
I could do the same for Access, not creating the DB but taking care of keeping the original mdb file untouched.
Also I'm refactoring DBConnectionTest to one class per vendor, removing the if tests sending `isAccessDB`

**Comment by fxgallego** [comment]
@blairmcg I refactored the DBConnectionTests this way https://github.com/fxgallego/Dolphin/tree/780_DBConnection_tests
What do you think?

I need to add something to skip when is not in CIBuild. But I don't like to add a skip in each individual test. I don't know if there is something better for entire test cases.
Also after this, I could start adding more tests, if you have some ideas let me know.

**Comment by blairmcg** [comment]
Seems good to me. I don't think we should run both in the CI build, however, as they are rather slow. They seemed to take longer to run than the other 6000-odd test cases put together. I would want to cut that down over time - I try not to have any individual tests that take longer than 500mS, otherwise over time we will accumulate a painfully slow build that it is then difficult to do much about.
There are various ways you can intervene in the test suite build to control what gets run, but probably the easiest way to skip an entire class of tests is to put a `skipUnless:` in its `setUp` method. I don't particularly see the need to skip these tests except on the CI build, however, only if SQL local DB isn't present.
There is no need to add the .sql file to LFS. It's text so although large it won't inflate the repo if changed.

**Comment by fxgallego** [comment]
OK. I'll give a look at the tests duration. I added the TestResources trying to mitigate that problem. The case for SQLServer is the worst because a database has to be created from scratch, but in the other hand, today has more value test against SQLServer than Access, although they are essentially doing the same thing. One thing I'm doing is getting a new connection for each test so maybe I could change that.
I don't know which one you prefer to run in CIBuilds, or none.

**Comment by blairmcg** [comment]
I don't think it is worth bothering with Access really. SQL server makes more sense for any serious use. We can speed it up incrementally (including paring back the data, or another smaller more recent sample DB if we can find a good one). I wouldn't worry about it unduly now though. It's good to move forward incrementally.

**Comment by blairmcg** [comment]
I tried out your branch, but sqllocaldb was not installed on my machine so I took advantage of that to make some adjustments to skip the tests in that case. I also found that the Access tests ran in about 300mS. I don't know what you did to improve that, but that is massively better.
I pushed your branch with the revisions to the Dolphin repo under its original name and both sets of test ran successfully on the appveyor machine, adding no more than a few seconds to the overall runtime. Frankly that is within the existing variability anyway. If you are happy with it I suggest you PR it as is, and then make any further changes you want to make as increments on that. What you've done looks easily good enough to me to consider this issue "fixed".

**Comment by fxgallego** [comment]
Ok I'll be happy with this as is, so no problem. Maybe later we can ad some methods.
I don't know what I did 😃 I've only added the databases as Resources so probably in the previous version, the database initialization was run for each test.
I'll send you the PR but with the appveyor.yml file with minimal changes
