### ISSUE TITLE
[Wine] Search Bar hidden when icons less than 24x24

### ISSUE THREAD

**Issue by brickviking** [dolphinsmalltalk/Dolphin#801]
**Bug**
If icon sizes (Preferences) are set to their default of 16x16, search bar is inaccessible. At  20x20 and 24x24, its top is visible, and above that size (32x32 and greater), the whole search bar is visible but isn't centred vertically.

**To Reproduce**
1. Start Dolphin under Wine
2. Look for Search Bar to the right of the (perhaps missing) IdeaSpace icon.
3. Select Preferences in System Browser
4. Select Development System
5. Scroll down to toolbarBitmapSize, set to various sizes to see the differences.
5a. Also note that the toolbar holding the buttons for the ViewComposer, Transcript, Visual Object Finder and  IdeaSpace icons shifts down to the next line when the bitmap size is increased. I've checked this over on Vista to confirm, as the picture shows.

**Expected behavior**
Start Dolphin, Search bar in each window should be vertically consistent with the rest of the toolbar at each bitmap size.

**Screenshots**
_System Folder (Vista and Fedora) when toolbarBitmapSize := 32@32_

![DolphinComposite32x32](https://user-images.githubusercontent.com/62885/62461564-4f6f6f00-b7d9-11e9-90d0-f69e8f49659f.png)

**Operating System:**
 - OS/Wine: 64-bit Fedora 28, wine-4.8-staging from WineHQ, 32-bit .wine directory with winetricks gdiplus, dotnet35 and vcrun2015.

(Further edits may be added)

**Comment by brickviking** [comment]
A further note to this bug (finally); sorry it's taken so long to find some of this out. From what I can tell, the issue's actually external to wine itself, as I can get the search bar to appear in the normal location when *not* running under Gnome-Shell or Gnome 3 classic. I have (so far) tried KDE (Plasma), xmonad, Gnome3-Shell and Gnome3-classic. Most Ubuntu users would probably be using GnomeShell by now, as Unity is no longer really a thing.

I have also had some success if I turned off settings in winecfg for "Let window manager manage windows" and "Let window manager decorate windows". It's a bit dubious whether using a virtual desktop works or not, so I won't recommend one or the other. So, stick an "External" flag on it for the moment, and I can't confirm or deny that wine has any involvement.

**Comment by blairmcg** [comment]
I'm closing this because it is going nowhere and I have no means or intent to progress it myself.
