### ISSUE TITLE
DBOOT.sml under Core/Object Arts/Dolphin/Base/Boot is LFS pointer, not original file

### ISSUE THREAD

**Issue by brickviking** [dolphinsmalltalk/Dolphin#812]
**File at Core/Object Arts/Dolphin/Base/Boot/DBOOT.sml is far too short**
This file should be large (2,247,450 bytes or thereabouts) not 88 bytes (or 130 bytes).

All the other LFS files were retrieved happily, but this one seems to have gone walkabout.

I've also noted that the 7.0 branch lists the file as the original size (2.08MB).
I'm not exactly sure what's going on here, but I'm wondering if this file would affect the booting process to create images.

**Comment by blairmcg** [comment]
This is a local problem with your git repository. To verify this I did a fresh clone into a temporary area:
```
D:\dev\blairmcg\temp>git clone https://github.com/dolphinsmalltalk/Dolphin.git
Cloning into 'Dolphin'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 37487 (delta 16), reused 15 (delta 8), pack-reused 37447
Receiving objects: 100% (37487/37487), 92.94 MiB | 8.70 MiB/s, done.
Resolving deltas: 100% (26071/26071), done.
Updating files: 100% (4593/4593), done.
Filtering content: 100% (23/23), 6.52 MiB | 1.56 MiB/s, done.

D:\dev\blairmcg\temp>cd Dolphin

D:\dev\blairmcg\temp\Dolphin>dir dboot.sml
 Volume in drive D has no label.
 Volume Serial Number is 1A56-A36F

 Directory of D:\dev\blairmcg\temp\Dolphin

23/08/2019  17:29         2,454,444 DBOOT.sml
               1 File(s)      2,454,444 bytes
               0 Dir(s)  1,638,099,484,672 bytes free
```
You can either take a fresh clone yourself, or try repairing it. Assuming you have nothing modified you want to keep a `git reset --hard` should work, or failing that look at the git lfs commands.

**Comment by brickviking** [comment]
You've shown the DBOOT.sml at the top of the tree. I'm talking about the one buried down in 
> Core/Object Arts/Dolphin/Base/Boot/DBOOT.sml,

which comes up as 88 bytes for me even after a fresh clone. I don't think it's a problem external to Dolphin.
```
$ ls -l Dolphin/DBOOT.sml
-rw-rw-r--. 1 viking viking 2454444 Aug 24 13:52 DBOOT.sml

$ ls -l Dolphin/Core/Object\ Arts/Dolphin/Base/Boot/DBOOT.sml
-rw-rw-r--. 1 viking viking      88 Aug 24 13:52 DBOOT.sml

$ cat  Dolphin/Core/Object\ Arts/Dolphin/Base/Boot/DBOOT.sml
oid sha256:beda488f3dcce08e1eb954359d164960dfd1b1d11031084a050d7eddefeccf16
size 2247450

```

I hope this makes things a little clearer. In addition, I can't find that hash in the LFS store, nor the object store inside .git. I also can't find an object with that number of bytes in either the LFS store or the object store inside the .git tree. Something seems weird.

**Comment by blairmcg** [comment]
Right, I see. It's correctly formed from an LFS point of view (`git lfs ls-files` lists it), but GitHub has lost the LFS file for some reason (seems unlikely), or there was a problem when it was pushed. I have seen occassional glitches with LFS when rebasing, but intermittently. Regardless of that it doesn't really matter as this is part of a mechanism to update the boot image that is no longer used. Any changes that need to be made to the boot image can just be added to the PreBoot.st script. Occasionally I consolidate these in. We should clean this up though, as it is confusing.

**Comment by brickviking** [comment]
I found a commit (d05c0195fdb824a5b4cb174ec3bbdd66ca075108) which was the last time the file was available at its original size (or thereabouts). The hash is different, and the size is different from the one in the later LFS pointer, but it's a lot closer.
