### ISSUE TITLE
Chunk Browser toolbar images corrupt when system tool bitmap size option is changed from 16x16

### ISSUE THREAD

**Issue by blairmcg** [dolphinsmalltalk/Dolphin#820]
When the system option to change the default toolbar bitmap size in development tools is changed from the default 16x16, the toolbar of the chunk browser shows corrupt images

This is because it uses a toolbar with images populated from a bitmap image strip of fixed size, rather than individual icons, and so can only serve up a single fixed size. Ideally the toolbar would recognise this and still display in the natural size of the bitmaps, but I'm not sure how simple this would be. A simpler alternative would be for this tool to ignore the setting.

**Repro Steps**

1. From the System Folder menu bar execute the command Tools/Options/Inspect Options...
1. Select 'Development System' from the left 'System Options' pane
1. In the right pane scroll down and double click 'toolbarBitmapSize'
1. Choose a size other than 16x16 and press the Ok (tick) button
1. From the System Folder menu bar execute the command Tools/Additional Tools/Chunk Browser

**Expected result**

![image](https://user-images.githubusercontent.com/15128107/64196982-e6812280-ce7c-11e9-9381-c7fc50fb8f1e.png)

**Actual result**

![image](https://user-images.githubusercontent.com/15128107/64196925-ca7d8100-ce7c-11e9-9654-698e2444e0ac.png)

**Comment by brickviking** [comment]
I'll see what I can do. I can't guarantee decent scaled bitmap icons, but I can at least separate them into their individual elements for the initial 16x16 size. It might take me a few days with the GIMP to create the icons in other sizes.

**Comment by brickviking** [comment]
Okay. I've generated basic pixmaps at all seven sizes for 24 icons. Do you want me to drop them into my repo and issue a pull request? They're all of the form offset-size.png where offset is the bitmap offset within the toolbar, and size is one of 16,20...64. They're not pretty, but it's something to work with, at least.

**Comment by blairmcg** [comment]
I think the best thing to do in this case would be to replace the system bitmap icons with other suitable icons from the Dolphin set (there are direct replacements for most, if not all), and to use TextTileIcons for everything else. As the existing icons are mainly just text with a color accent, it won't be much of a visual degradation, and that way all the hard work (and believe me, it is very time consuming) of painting up proper icons can be permanently avoided.

**Comment by brickviking** [comment]
Sounds great. Okay, I'll junk this set then.
