### ISSUE TITLE
Dolphin7.exe fails to start due to ucrtbase.dll error

### ISSUE THREAD

**Issue by wuya666** [dolphinsmalltalk/Dolphin#828]
**Describe the bug**
Dolphin installed with the v7.1.4 release Setup Installer won't start as it fails silently due to some ucrtbase.dll error

**To Reproduce**
1. Install Dolphin with the v7.1.4 Setup Installer
2. Run the Dolphin Smalltalk program from Start Menu
3. Nothing happens
4. Open the Event Viewer from Windows system administration tools, and there's an Application error message with something about ucrtbase.dll

**Expected behavior**
The program should start, or at least report some error messages on why it cannot start and give some hint on how to fix the issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/30381159/66701231-a12dfb80-ed2c-11e9-9115-b95bdf680743.png)

**Please complete the following information):**
 - OS: Windows 10 Professional 1903 64-bit

**Additional context**

**Comment by brickviking** [comment]
Do you happen to have vcrun2017 installed? That's one of the prerequisites for this program.

**Comment by wuya666** [comment]
> The ucrtbase.dll comes from the Visual Studio Redistributable Components 2015, do you happen to have these installed? That's one of the prerequisites for this program. As this is currently a 32-bit program, you'll need vcredist_x86.exe for that version. A later version (say, 2017 or 2019) may also work. They're available from microsoft.com in the downloads centre.

I already have the "Microsoft Visual C++ Redistributable (x86)" thing installed on my system, and still Dolphin won't start and there's the ucrtbase.dll error in the Event Log.

![image](https://user-images.githubusercontent.com/30381159/67158459-d65cce00-f36a-11e9-956d-706132be78d5.png)

**Comment by syosetu** [comment]
Windows 10 Pro / 64bit / Japanese

Reproduced in my environment.
However, in my environment, I was able to run Dolphin 7.1.4 by changing the system locale from Japanese to English‪(United States)‬.

**Comment by brickviking** [comment]
> Same here on my Win10 Pro. Tried these components one by one just to fail with Event 1000.

Which version of Windows 10 are you running currently? i.e. what update level? Recently Microsoft has released 1903, I'm wondering if this has updated ucrtbase.dll, as that's supplied as part of the base OS as well as in the C Runtime Libs.

I don't run Windows 10 here myself, so I can't actually help out much more than to google results.

**Comment by iriyak** [comment]
> Which version of Windows 10 are you running currently?

Mine include:

* Windows 10 Professional 1803 64-bit. 
* Windows 10 Professional 1809 64-bit. 

Glad to be of help if there is any other action to take in the short term.

By the way I verified to work Dolphin X6.1 beta worked on both environments.

**Comment by wuya666** [comment]
> Windows 10 Pro / 64bit / Japanese
> 
> Reproduced in my environment.
> However, in my environment, I was able to run Dolphin 7.1.4 by changing the system locale from Japanese to English‪(United States)‬.

I already set my Windows system locale to English(United States) but still not working.

**Comment by Jaystings** [comment]
Hello, I have been experiencing an C:\windows\System32\ucrtbase.dll error as well this month. I isolated my problem to running it after using the window button to search for the app's shortcut and executing it from there. I use Windows 11 Home. 

Running the app by clicking on the shortcut or the app itself works just fine. I hope this helps, but am still curious as to what exactly is happening and how I can start running the app by just searching for it with the OS again. I await any replies.

**Comment by blairmcg** [comment]
It's really not possible to diagnose such an issue without more information. As a general rule try and locate the Dolphin error log, which generally gets written alongside the image. If you don't know where this is, run a debug output tool such as the sysinternals debugview from https://learn.microsoft.com/en-us/sysinternals/downloads/debugview. The Dolphin VM will write some debug output that provides the path of the log before it writes to it. If it doesn't get that far, i.e. the system is failing to start at some deeper level, then there will be no output. In that case it might be because your search may be finding an old version from an old installation that fails as above. Check the system event log per the above to see which version is faulting and where the launcher is running from.
