### ISSUE TITLE
[object-arts.com] Error: invalid SSL certificate (out of date)

### ISSUE THREAD

**Issue by brickviking** [dolphinsmalltalk/Dolphin#829]
When heading off to Object Arts (https://object-arts.com/gettingstarted.html), I get the following data:
>Your connection is not private
Attackers might be trying to steal your information from object-arts.com (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID
>
>Help improve Safe Browsing by sending some system information and page content to Google. Privacy Policy
This server could not prove that it is object-arts.com; its security certificate expired 41 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Sunday, 13 October 2019. Does that look right? If not, you should correct your system's clock and then refresh this page.

Hope this gets passed up to the right place (please prod the maintainer of object-arts.com), as I can't select labels from this issue screen and it's not strictly a Dolphin bug.

**Comment by blairmcg** [comment]
Not a Dolphin issue, sorry.
