### ISSUE TITLE
CodeMentor reports undeclared variables for all pool constants

### ISSUE THREAD

**Issue by blairmcg** [dolphinsmalltalk/Dolphin#852]
One of the Code Mentor's code analysis rules looks for references to undeclared variables. 

Traditionally in Smalltalk-80 and descendants it was not a compilation error to refer to an undeclared variable, rather a warning was given and the variable was defined as a global in the special `Undeclared` pool. This rather lax approach allowed for loading code out of order and not having to manage dependencies properly. One practical outcome of this is that it is not unusual for architectural layers to be poorly defined in packaged Smalltalk code, or even for circular dependencies to exist between such layers. When designing Dolphin we considered (and still consider) this a very bad idea, so there is no Undeclared pool in Dolphin. The Dolphin compiler will treat all undeclared variables as errors and refuse to compile the offending methods. 

Undeclared variables can still arise in Dolphin as a result of modifications made to class or pool dictionaries (or the system dictionary) after code has been compiled, for example, deleting a class variable that is still referenced in methods from the class definition, but this is much less likely than Undeclared variables from supposed forward references that are actually typos, or in code that is never loaded, and so never actually get defined. Consequently this particular code analysis rule is not especially useful in Dolphin, but nevertheless it ought not to report false positives.

The underlying issue is that the rule searches for bindings that are an exact (identical) match with the bindings for static variables stored in the literal frames of compiled methods. PoolConstantsDictionary instances in Dolphin do not actually store variable bindings, but create them on the fly to satisfy binding requests, and consequently an identical match will not be found.

**To Reproduce**
1. Execute a 'Browse It' command on `GdiplusImage`
2. Select the Code Mentor tab
3. Notice that 'Variable used, but not defined anywhere` is listed as a possible bug, with 6 occurrences.
4. Select the issue in the tree on the left and then click on the title link in the explanatory pane on the right
5. Examine the `frameDimension` method in the resulting method browser, and note that it references two pool constants. It is these that are being reported, but they are declared.

**Expected behavior**
GdiplusImage does not contain any undeclared variable references, and so the code mentor should not be reporting any.

**Screenshots**

![image](https://user-images.githubusercontent.com/15128107/69753072-8da6ea80-114a-11ea-9639-ca070097a8a5.png)

**Comment by jgfoster** [comment]
This commit seems to have broken Jade (or exposed a pre-existing hidden bug in Jade!). See https://github.com/jgfoster/Jade/issues/250. Specifically, it seems that FFI calls now behave differently and we get errors like GPF on things that previously worked. Any suggestions on what to investigate? From reading the description it seems that this change should only change the CodeMentor behavior.

**Comment by blairmcg** [comment]
Not this commit (which is indeed only about the issue described), but bcee95e identified by Bruno, does change the behaviour of an error case in StructureArray>>with:do:. I'll comment on that in reply to him.

**Comment by blairmcg** [comment]
@jgfoster, I tried installing GS to see if I could debug through this to find the issue. I used your instructions at https://programminggems.wordpress.com/2018/08/27/gemstone-s-64-bit-on-windows-10/. I managed to work through version related problems communicating with the netldi, but then ran into the issue that the stone won't start because of a "cpuAffinityViolation". I couldn't work out how to configure things to use only 2 CPUs as required by the community license, so I had to give up at that point.

**Comment by jgfoster** [comment]
@blair, Not that you have to continue this path, but I'll send you a key file allowing a larger number of cores.
Also, I tried building with your most recent commit and it still fails. Also, I've confirmed that I'm able to run with the commit before this so it remains a mystery. I'm continuing to investigate what change in this commit might have caused the problem.

**Comment by blairmcg** [comment]
Ok, thanks James. The commit did include an update of the boot image - I think I probably did that because of the change to the compiler to always store the bindings for constants in the literal frame of methods, even if not used in the bytecodes, in order to make the reference finding reliable. Changing the way constant refs are stored/searched for would probably have made the old boot image fail on the first attempt to search for methods to recompile when setting the value of a constant on class initialisation. This did make we wonder if there might be problems with the sizes of any external struct definitions you have, or offset to fields? It's worth checking those are right in the booted image, and maybe doing an `Object recompileAll`

**Comment by brunobuzzi** [comment]
@jgfoster @blairmcg `Object recompileAll` fixed the bug. After executing that Jade works with Dolphin latest commit.

**Comment by jgfoster** [comment]
@blairmcg, Thanks for your time and help on this. While it is very plausible that I have some wrong offsets (I'm trying to model several external structures that aren't using explicit int sizes), I'm not sure how to find them. Furthermore, if the recompile fixes the problem does that there wasn't a problem or that I've masked it?

**Comment by brunobuzzi** [comment]
@jgfoster the login problem is fixed but more is going on...
Because i'm not able to debug GS code. Try to debug any expression and you get and error.
Also searching for classes has some errors

**Comment by jgfoster** [comment]
@brunobuzzi, Let's take the subset issues to the Jade project until we have more evidence of a Dolphin problem...

**Comment by blairmcg** [comment]
Hmmm, I'd be worried it is just masked too, especially without understanding why its been fixed. If the code loading were failing to recompile something it should (which is possible, since that was changed), then you would normally expect that evaluating `Smalltalk developmentSystem browseMethodsWithNewBytecodes` would find something. It didn't when I tried it. It may be that recompiling has just shuffled stuff around enough to avoid anything important getting corrupted. 
There's no easy way to be sure the structures are correctly defined. You need to be sure of the sizes and the packaging of the structure. Dolphin's structure generator will assume a standard Windows packing arrangement, but sometimes this is overridden in the header files so it may not be right.  I usually build a typelib out of them and generate from that, but that is some work, especially if you aren't used to doing it. Failing that you could build a C console program with the header files from the SDK, and dump out offsets, etc, from that.
