### ISSUE TITLE
Clean up improperly imported categories

### ISSUE THREAD

**Issue by daniels220** [dolphinsmalltalk/Dolphin#860]
The base image contains a number of categories whose names begin with `private/` or `private-`, primarily on methods in the RB* and IDB* packages. Confusingly, some of these methods are also marked public. Since Dolphin can assign multiple categories to a method, it seems like a method in e.g. `private/transforming` should instead be private and in category `transforming`. If this seems reasonable, I can go ahead and make a PR for the change. For reference, the full list of such categories is:

* private/accessing
* private helpers
* private/transforming
* private / actions
* private/methods
* private/changes
* private-replacing
* private/variables

**Comment by blairmcg** [comment]
Originally we deliberately preserved these as is in order to minimise change when importing/exporting the code. That is probably no longer relevant, so I think it would be fine to remap them to represent the categorisation properly.

**Comment by blairmcg** [comment]
Fixed by #863
