### ISSUE TITLE
assert failure at compiler.cpp:3456

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/Dolphin#864]
**Describe the bug**
I accidentally built Dolphin using debug mode and got an assertion failure.

**To Reproduce**
Build in debug mode and launch BuildDPRO.cmd

**Expected behavior**
Dolphin launches and runs correctly (though slower).

**Screenshots**
![Screen Shot 2020-02-20 at 6 38 11 PM](https://user-images.githubusercontent.com/1577872/74999314-29758900-5410-11ea-8e97-c7c5396d788c.png)

**Please complete the following information):**
 - OS: Windows 10

**Additional context**
textStop is -1, which is less than 0 (TextLength), but the comparison casts textStop to size_t, which is unsigned, so we fail because 4294967295	is not less than zero.

**Comment by blairmcg** [comment]
Thanks James, good bug report. I don’t think it is a signed unsigned mismatch though because both values are size_t (after casting). Rather the values are equal, failing the less than assertion. 
Do you have an example method this fails on as that would help me work out whether it is valid assertion finding a bug, or just an invalid assertion.

**Comment by jgfoster** [comment]
Hi Blair, the assertion is hit during the BuildPRO.cmd process, so I don't have an example method. The boot process crashes almost immediately.

As to the comparison, it appears to me that the values are _not_ equal. The end is -1, and the length is 0. When the end is converted to unsigned it becomes 4294967295, so now the end is (much) greater than the length, triggering the assertion.

**Comment by blairmcg** [comment]
Ok, I was just looking for a repro. That's perfect.

Sorry, I was confused by your screenshot, which doesn't show the original code. I'll fix the assertion.

**Comment by blairmcg** [comment]
Fixed by 9805376
