### ISSUE TITLE
Inspect a regular expression fails

### ISSUE THREAD

**Issue by brunobuzzi** [dolphinsmalltalk/Dolphin#87]
IRegExp pattern: '[0-9]' .  "inspect it" 
"evaluating works fine"

This fails with a couple of doesNotUnderstad messages:
IRegExp>>argSizes
IRegExp>>interfaceCookie
IRegExp>>objectCookie
IRegExp>>vtbl

**Comment by brunobuzzi** [comment]
I will create a Pull Request but here is the code for COMInterface (4 methods added)
COMInterface
argSizes
	"Get the receiver's argSizes field"

	bytes uintPtrAtOffset: ##(self offsetOf: #argSizes)

interfaceCookie
	"Get the receiver's interfaceCookie field."

	bytes dwordAtOffset: ##(self offsetOf: #interfaceCookie)

objectCookie
	"Get the receiver's objectCookie field."

	bytes dwordAtOffset: ##(self offsetOf: #objectCookie)

vtbl
	"Get the receiver's vtbl field"

	bytes uintPtrAtOffset: 0

**Comment by blairmcg** [comment]
@brunobuzzi, I think this is a more general issue with the published aspect inspector when examining instances from the ExternalStructure hierarchy. These fields, which are internal implementation data, have been left without accessor methods deliberately. The PAI should be skipping these fields as they are not public aspects. At one point this used to work, and must have regressed.

**Comment by brunobuzzi** [comment]
@blairmcg Ok, i will take a look at the PAI maybe i can find the general error !

**Comment by brunobuzzi** [comment]
The problem is in the implementation of:
ExternalStructure>>publishedAspects
...
self getValidFields "answer the offending fields"
"an OrderedCollection(#vtbl #argSizes #objectCookie #interfaceCookie)"

If the following code is commented the issue is fixed:
"	self isNull 
		ifFalse: 
			[self getValidFields do: 
					[:each | 
					| field |
					field := self template at: each.
					aspects add: (field newAspect: each class: Aspect)]]."
No idea why this was added but commenting this will make the inspection work properly.
Or simple remove the method ExternalStructure>>publishedAspects.
regards
bruno

**Comment by blairmcg** [comment]
@brunobuzzi, the ExternalStructure>>publishedAspects method is trying to make the inspector that opens on an ExternalStructure more useful by including all the fields. This makes sense if you think about it, otherwise you are just going to see a load of bytes. The issue is that it is including all the fields on the assumption that they are all readable, but they may not be. So you are in the right area, but the right fix will be something like this:
```
publishedAspects
	"Answer a &lt;LookupTable&gt; of the &lt;Aspect&gt;s published by instances of the receiver."

	| aspects |
	aspects := super publishedAspects.
	self isNull 
		ifFalse: 
			[self getValidFields do: 
					[:each | 
					| field |
					field := self template at: each.
					field isReadable ifTrue: [aspects add: (field newAspect: each class: Aspect)]]].
	^aspects
```

**Comment by brunobuzzi** [comment]
@blairmcg it seems that your solution if the correct one.

Initially i thought that "isInaccessible" should be included in you solution but after a little research "isInaccessible" is filtered in "getValidFields" via "getFieldList".
I have create a Pull Request with this change.
Thanks blair
