### ISSUE TITLE
String>>subStrings: not symmetric in treatment of leading/trailing separators

### ISSUE THREAD

**Issue by blairmcg** [dolphinsmalltalk/Dolphin#877]
`'-a-bc' subStrings: $-` => `#('' 'a' 'bc')` (correct)
but
`'a--bc-' subStrings: $-` => `#('a' '' 'bc')` (should be `#('a' '' 'bc' '')`)

This is inconsistent. A separator not preceded or followed by a non separator should yield an empty entry in the list of substrings, no matter whether it is at the start of the string, in the middle of the string, or at the end of the string.

The following should also be true:

`('-' subStrings: $-) = #('' '')`

Note that fixing this is a breaking change.

**Comment by fxgallego** [comment]
I've just surprised by this behavior change.

For the record **`String>>subStringsAnsi:`** has backwards compatibility, I don't know if by design or bug.

I checked Pharo 6.1, 8, JavaScript and Ruby only to know how they behave.
**JavasScript:** It returns the same as Dolphin returns now.
**Ruby:** It returns the same as Dolphin returned before this change, the same as `subStringsAnsi:`
*Note that both, JavaScript and Ruby, have a second parameter for `split()` that allows to change this behavior.*
**Pharo:** It never returns empty Strings so `'-' substrings: '-'` returns an empty Array. Also note the method name is `substrings:`

**Comment by blairmcg** [comment]
`subStringsAnsi:` is referring to the ANSI Smalltalk description of `subStrings:`, rather than having anything to do with the `AnsiString` class. The key difference being that the ANSI Smalltalk definition expects a collection of separators (not a single character - so `subStringsAnsi:` should also be raising an error when passed a single character) as being "any of" not "all of", although other than that the spec is really rather ambiguous. I'd have expected it to be covered by the ANSI tests, but the corresponding test method in the CS ANSI tests is basically empty.

In Pharo the `String>>splitOn:` operation (or the underlying `Object>>split:`) is the equivalent:

```smalltalk
'-' splitOn: $-. "an OrderedCollection('' '')"
'-c-' splitOn: $-. "an OrderedCollection('' 'c' '')"
```

The operation is symmetric with `Character>>join:` so the following should be true: 

```
input := '-c-'. ($- join: (input subStrings: $-)) = input
```

The behaviour change to fix the historic bug of not treating leading and trailing separators symmetrically does break a few use cases. Trimming empty tokens by default would probably break the majority of existing use cases, but it would be useful to have the option.

**Comment by fxgallego** [comment]
I'm Ok with the change. Just revising some broken tests with the latest Dolphin release  on our development branch.
So if I understood well you'll change `subStringsAnsi:` to the same behavior of `subStrings:`, with the difference in the argument only.

I like the `join:` symmetric concept. Also as `split:` is implemented in `Collection` and `String` a symmetric `join:` would be useful replacing simple uses of `do:separatedBy:`. We implemented it as an extension but in the opposite direction, for example: `#('Hello' 'World' '2020') join: ' ' ` that's the same as in Ruby.

**Comment by fxgallego** [comment]
I'm correcting my own failing tests and find that there are some use cases for `subStrings:` trimming empty tokens. As @blairmcg said:

> Trimming empty tokens by default would probably break the majority of existing use cases, but it would be useful to have the option.

I'd like to have that option. `nonEmptySubStrings:` ?? or maybe `subStrings:limit:` and adhere to JavaScript [split()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split), I don't know. I have 2 examples where I found it could be handy:
1. Get tokens of a keyword selector, for example 'at:put:' subStrings: $: 
1. Sometimes we get a list separated by $, or other separator char but there is a trailing extra separator so you end with an extra ''

**Comment by fxgallego** [comment]
JavaScript split() with limit doesn't seems to be useful in this case...
`trimBlankSubStrings:`, `subStringsTrimmed:`, `rejectEmptySubStrings:`
An also, only leading and trailing should be removed I guess. I'm starting to think that's better to keep only one version as it's working now and left people work around their own necessities.
