### ISSUE TITLE
RegKeyAbstract new code causes regression in XMLPad with mismatched VM

### ISSUE THREAD

**Issue by brickviking** [dolphinsmalltalk/Dolphin#879]
**Describe the bug**
Trying to start up XMLPad gives me a debug box thing, saying it can't find relevant registry key. It's trying to load the following regkey:
HKEY_CURRENT_USER/Software/Object Arts/XmlPad/TextStyles

**To Reproduce**
1. Go to 'Sample Applications'
2. Click on 'XMLPad'
3. Box pops up, title: Not found: 'A'
text reads:
25/04/2020 12:17:32 a.m.: 'Not found: A'
SystemDictionary(Object)>>errorNotFound:
SystemDictionary(Dictionary)>>errorKeyNotFound:
SystemDictionary(Dictionary)>>at:
Object class>>fromRegKey:
[] in XmlPad>>restoreTextStyles
RegKey(Dictionary)>>at:ifPresent:
XmlPad>>restoreTextStyles
XmlPad>>restoreViewOptions
XmlPad>>restoreUserSettings
XmlPad(TextDocument)>>onViewOpened
XmlPad(Shell)>>view:
XmlPad(Shell)>>createView:
XmlPad class(Shell class)>>create:
XmlPad class(Presenter class)>>create
XmlPad class(Presenter class)>>show
[] in SmalltalkSystemIcon>>openBlock
[] in SmalltalkSystemIcon>>openIn:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
Cursor>>showWhile:
SmalltalkSystemIcon>>openIn:
[] in System Folder>>createComponents
FolderPresenter>>onActionPerformed
ListView(View)>>performAction
FolderPresenter(Presenter)>>performAction
ListView>>onLeftButtonDoubleClicked:
FolderPresenter(Presenter)>>onLeftButtonDoubleClicked:
ListView(View)>>wmLButtonDblClk:wParam:lParam:
ListView(View)>>dispatchMessage:wParam:lParam:
[] in InputState>>wndProc:message:wParam:lParam: cookie:
BlockClosure>>ifCurtailed:
GuiInputState(InputState)>>wndProc:message:wParam:lParam: cookie:
ShellView(View)>>isDialogMessage:
ShellView>>preTranslateMouseInput:
ShellView(View)>>preTranslateMessage:
GuiInputState(InputState)>>preTranslateMessage:
GuiInputState(InputState)>>pumpMessage:
GuiInputState(InputState)>>loopWhile:
GuiInputState(InputState)>>mainLoop
[] in GuiInputState(InputState)>>forkMain
ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry
[] in ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
ExceptionHandler(ExceptionHandlerAbstract)>>try:
BlockClosure>>on:do:
[] in BlockClosure>>newProcess:

I started by inserting a halt into XmlPad>>restoreTextStyles and walking forward until things went pearshaped, which they appeared to do by the time we finished with Object class>>fromRegKey:

the line I can find where things go bad is:
params := aRegKey value. This (eventually) calls decodeMultiSz.
String class>>fromByteArray:length:startingAt: returns an answer of 'Array*30'  (* is the \0 character). This appears to be correct, but I could be misinterpreting it.

Investigations show that #('Array' '30') gets eaten and ends up becoming #('A' 'r' 'y' '3'). I suspect things are getting eaten by decodeFrom:upTo: but I don't know why.

**Operating systems:**
 - OS: Windows Vista, Fedora 28
 - Git version: v7.1.10-44-g54eb3494

**Comment by blairmcg** [comment]
This is what you would see if you'd not rebuilt the VM. The decoding of REG_MULTI_SZ is covered by RegKeyTest>>testMultiSz (which decodes an object serialised into the registry in the exact same way), so that would be failing if this were an actual bug.

**Comment by brickviking** [comment]
I snagged a copy of the VM for DolphinVM-v7.1.10, extracted that, still got the same result when I opened up the image. Do I need to rebuild the image too?

**Comment by blairmcg** [comment]
Yes, that will work. If you want to work with the source code direct from the repo, then in order to have matching code either rebuild the VM yourself, or grab the artefacts from the corresponding master build as you did. Obviously this won't be necessary if there are no changes to the VM code since the last time you built/downloaded it.
