### ISSUE TITLE
Regression in DCORE.img7

### ISSUE THREAD

**Issue by brickviking** [dolphinsmalltalk/Dolphin#891]
First, a bit of history.  I kept the ability to create DCORE/DBASE etc, as I can see a possible benefit to starting from a far smaller subset and building on that rather than stripping out from a complete image. But now that's bitten me.

I generated a DCORE recently, but when I tried running it, I got this walkback:

>9/05/2020 9:14:19 p.m.: 'ListView does not understand #smallImageExtent'
ListView(Object)>>doesNotUnderstand:
ListView>>applyImageLists
ListView(IconicListAbstract)>>onViewCreated
ListView>>onViewCreated
ListView(View)>>createAt:extent:
MessageSend(MessageSendAbstract)>>value
[] in MessageSequenceAbstract>>value
OrderedCollection>>do:
MessageSequence>>messagesDo:
MessageSequence(MessageSequenceAbstract)>>value
ListView(View)>>state:
ListView(STBViewProxy)>>restoreView
[] in STBViewProxy>>restoreView
Array(ArrayedCollection)>>do:
ContainerView(STBViewProxy)>>restoreView
[] in STBViewProxy>>restoreView
Array(ArrayedCollection)>>do:
ShellView(STBViewProxy)>>restoreView
ShellView(STBViewProxy)>>restoreTopView
[] in ShellView(STBViewProxy)>>stbFixup:at:
[] in STBInFiler>>evaluateDeferredActions
OrderedCollection>>do:
STLInFiler(STBInFiler)>>evaluateDeferredActions
STLInFiler(STBInFiler)>>next
ResourceIdentifier>>loadWithContext:forEdit:
ResourceIdentifier>>loadWithContext:
SmalltalkSystemShell class(Presenter class)>>loadViewResource:inContext:
SmalltalkSystemShell(Shell)>>createView:
SmalltalkSystemShell class(Shell class)>>create:
SmalltalkSystemShell class(Presenter class)>>create
SmalltalkSystemShell class(Presenter class)>>show
SmalltalkSystemShell class(SmalltalkToolShell class)>>show
SmalltalkSystemShell class>>default
SmalltalkSystemShell class>>onStartup
DevelopmentSessionManager>>tertiaryStartup
[] in DevelopmentSessionManager(SessionManager)>>onStartup:
BlockClosure>>ensure:
[] in DevelopmentSessionManager(SessionManager)>>onStartup:
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
DevelopmentSessionManager(SessionManager)>>onStartup:
ProcessorScheduler>>onStartup:
[] in ProcessorScheduler>>vmi:list:no:with:
BlockClosure>>ifCurtailed:
ProcessorScheduler>>vmi:list:no:with:
[] in UndefinedObject>>{unbound}doIt
BlockClosure>>ifCurtailed:
BlockClosure>>ensure:
UndefinedObject>>{unbound}doIt
Compiler class>>evaluate:for:evaluationPools:logged:ifFail:

I think I've traced it to b4e59a2a7ba482b683db8a2e53ca0ef012c7df74 back when you were doing the ListView changes. DBASE appears to work fine, but DCORE is missing something that I can't put my finger on. I may have tracked it down to
Core/Object Arts/Dolphin/MVP/Common Controls/ListView.cls:146, which relies on bits being brought in from Contributions/Solutions Software/SSW ListView Extensions, from what I can tell, those aren't brought in when compiling a DCORE image.

There's a lot I don't know about this, so this could just be a rabbit hole.

I would prefer the "fix" not to be simply removing the ability to create the smaller images, but I don't know what else to suggest here.

Regards, BrickViking (a.k.a DrSmokey)

**Comment by rko281** [comment]
`ListView>>#smallImageExtent` is an extension in SSW ListView Extensions but is referenced from `ListView>>#applyImageLists` which is in the base definition of that class (Dolphin Common Controls).

`ListView>>#smallImageExtent` should probably be moved to Dolphin Common Controls (and possibly renamed to `smallIconExtent` to match largeIconExtent).
