### ISSUE TITLE
Problem adding new key bindings

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/Dolphin#929]
I don't know if this is a bug but it started to happen some point after 7.1.11 tag. I guess it probably by a change in #919 .
We load a package called Intelli-Dolphin with some third part additions.
The package has a Class initializer that does something like this script:
```
bindings := SmalltalkWorkspace acceleratorKeyBindings.
bindings
	at: 'Ctrl+2' put: #commentSelection;
	at: 'Ctrl+0' put: #widenSourceSelectionAndBracket;
	at: 'Ctrl+-' put: #widenSourceSelectionAndBlock;
	at: 'Tab' put: #tabToNextItem;
	at: 'Shift+Tab' put: #tabToPrevItem;
	at: 'Ctrl+Enter' put: #autoCorrectTemp;
	yourself.
SmalltalkWorkspace acceleratorKeyBindings: bindings
```
The problem, as you can see in the attached image, is that each key in `acceleratorKeyBindings` is translated into Spanish, but when they set again the new extended accelerator table, the key is not recognized with the Spanish name. I guess you'll need other locale than English, and maybe, one that names SPACE with 2 words, to reproduce this.
I see that, as part of #919, maybe there is another better way to add key bindings so maybe this can be avoided. Also I'll not use anymore this package, so for me isn't a problem, but I wanted to let you know about the issue.

![image](https://user-images.githubusercontent.com/2080171/84191047-4a6cf300-aa6e-11ea-9a70-317672f7cfea.png)

**Comment by blairmcg** [comment]
Yes, that's useful to know thank you. Some care is taken to always look up key bindings using invariant names, but there must be a mistake there in the conversion somewhere that it is mixing up the keyboards.
