### ISSUE TITLE
Move to VS2015 has broken running under Wine

### ISSUE THREAD

**Issue by objectarts** [dolphinsmalltalk/Dolphin#93]
It seems that following the move to VS2015 and subsequent changes, Dolphin no longer runs under Wine. The error on startup is:

```
wine: Call from 0x7b83c3de to unimplemented function api-ms-win-crt-runtime-l1-1-0.dll._get_narrow_winmain_command_line, aborting
wine: Unimplemented function api-ms-win-crt-runtime-l1-1-0.dll._get_narrow_winmain_command_line called at address 0x7b83c3de (thread 0033), starting debugger...
wine@ubuntu:~/shared_directory$ Unhandled exception: unimplemented function api-ms-win-crt-runtime-l1-1-0.d._get_narrow_winmain_command_line called in 32-bit code (0x7b83c3de).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7b83c3de ESP:00c0fd64 EBP:00c0fdd8 EFLAGS:00000283(   - --  I S - - -C)
 EAX:7b827a69 EBX:7b8c0000 ECX:7e9ab044 EDX:00c0fd84
 ESI:80000100 EDI:00000000
Stack dump:
0x00c0fd64:  00c0fe00 00000008 7ea0eb99 80000100
0x00c0fd74:  00000001 00000000 7b83c3de 00000002
0x00c0fd84:  7e9ab044 7e9ab0ec 7ea93d00 00000001
0x00c0fd94:  7ea83000 f75fbdbb f7799000 00000000
0x00c0fda4:  f754ab6d 7ea83000 7ea344ce 00c0fde0
0x00c0fdb4:  00000000 00000044 7ea0854d 00000009
000c: sel=0067 base=00000000 limit=00000000 32-bit r-x
Backtrace:
=>0 0x7b83c3de in kernel32 (+0x2c3de) (0x00c0fdd8)
  1 0x7e9ab028 in api-ms-win-crt-runtime-l1-1-0 (+0xb027) (0x00c0fe10)
  2 0x7e9aaa2d in api-ms-win-crt-runtime-l1-1-0 (+0xaa2c) (0x00c0fe60)
  3 0x00401824 in dolphin7 (+0x1823) (0x00c0fe60)
```

This is with the latest (almost) bleeding edge version of *winetricks* installed and then using `winetricks -q vcrun2015` to install the 2015 runtime. Note that I was unable to use the very latest (as of today) *winetricks* because this has a syntax error in an ie8 function name. To get the prior version I used:

```
wget https://raw.githubusercontent.com/Winetricks/winetricks/dd1bff70e6f11338b63ee07e44ff28e76010885e/src/winetricks
sudo cp winetricks /usr/bin
sudo chmod +x /usr/bin/winetricks
```

The current workaround is to go back to using the [older 7.0.2 version of Dolphin](https://github.com/dolphinsmalltalk/Dolphin/releases/download/v7.0.2/Dolphin7Setup.exe) that was built with VS2015 but presumably before some incompatible changes.

**Comment by objectarts** [comment]
Actually, it seems that manually installing vcrun2015 via winetricks is enough to get this to work. Let me check and then I'll close this issue.

**Comment by vladvinnikov** [comment]
I have a similar problem with crossover on mac - this helped me to solve it: [](https://www.winehq.org/pipermail/wine-bugs/2015-November/428425.html)
