### ISSUE TITLE
ListView checkboxes not shown unless disabled/enabled with view showing

### ISSUE THREAD

**Issue by daniels220** [dolphinsmalltalk/Dolphin#967]
The `ListView>>hasCheckBoxes` style no longer seems to work when the view is created with the style already set—as when loading from a view resource, but it can be reproduced by creating the view manually as well. Evaluate:

```Smalltalk
(ListView new)
	viewMode: #report;
	isVirtual: false;
	hasCheckBoxes: true;
	model: (ListModel on: #(1 2 3));
	showShell.
```

Or, open `ListPresenter.Enhanced list view resource`, set `isVirtual: false` and `hasCheckBoxes: true`, and Save As... 'Checkboxes view'. Then execute `ListPresenter create: 'Checkboxes view' on: (ListModel on: #(1 2 3))`.

Either way, the result is a window containing a ListView that answers `true` to `#hasCheckBoxes`, but does not, in fact, have checkboxes—they aren't visible, and attempting to manipulate them using `LVM_{GET|SET}ITEMSTATE` does nothing and always returns 0. `self lvmGetExtendedListViewStyle allMask: LVS_EX_CHECKBOXES` is true, so it's not that the `lvStyle` ivar is out of sync with the actual style of the view.

Clearing and setting the style after the view is open makes it work, but this cannot even be done in `#onViewCreated` or `#onViewOpened`, it has to be done in a block `#postToMessageQueue`'d _from_ `#onViewCreated`, i.e. after the view is *really, truly* open and done with all message processing associated with the initial opening.

This happens on both Windows 7 and 10.

**Comment by daniels220** [comment]
Nice, thanks. Looks like the `NoImageIndex` class var is unreferenced now—should it be removed?

**Comment by blairmcg** [comment]
The references search should work for class constants now (as well as for class variable anyway). It didn't prior to f3cce4ebaded8de71b90ca2eccff4b3b77ba1928. I just tried it and it did find two other references to `NoImageIndex`.  There is still the issue that references from outside the local class hierarchy will not be found, as the search dates from when it wasn't possible to use qualified names to reference them from anywhere.

It's not really exchanging nil for zero that which fixes the problem with checkboxes. Or at least not entirely - that's just a part of the fix. nil makes it easier to identify when the state image indexes should be left alone for the ListView to manage, as opposed to being zero'd out explicitly to clear them, which is the desired behaviour when no image is wanted. So yes, there is a reason for them to be different.

The ListView checkboxes are still not what I would think of as a first class feature. There is no presenter support, or events, etc. I'm not sure its worth doing more without addressing other limitations such as making the feature work in virtual lists. If that were done I think it would be better just to manage the checkboxes from the Smalltalk side of things and forget the ListView style, even for the non-virtual mode.

**Comment by daniels220** [comment]
Oh cool—I'm working in a somewhat out-of-date image because of changes of my own that I have yet to merge with the latest.

Yeah, I can sorta see how that would work. Thanks again for the fix.

And yeah, I understand that the feature isn't terribly well-developed—I'm using them in a couple specific places where they work well enough for me, and don't particularly have plans to use them more at the moment, so just preserving the status quo is good enough.
