### ISSUE TITLE
ADODB_Command fails with String parameters

### ISSUE THREAD

**Issue by rko281** [dolphinsmalltalk/Dolphin#970]
An error occurs when attempting to use ADO with a parameterized query containing String parameters. 

The problem can be reproduced by replicating [this example](https://docs.microsoft.com/en-us/sql/ado/guide/data/command-object-parameters?view=sql-server-ver15) which uses the Northwind example Access DB (though I've also replicated the issue under MySQL so it doesn't appear to be Access-specific):

```
adoCommand := ADODB_Command new.
adoCommand
	commandText: 'SELECT OrderID, OrderDate, RequiredDate, ShippedDate FROM Orders WHERE CustomerID = ? ORDER BY OrderID';
	commandType: ADODBConstants.adCmdText;
	prepared: true.

param := adoCommand createParameter: 'CustID' type: ADODBConstants.adChar direction: ADODBConstants.adParamInput size: 5 value: 'ALFKI'.
adoCommand parameters add: param.

adoConnection := ADODB_Connection new.
adoConnection  connectionString: 'Northwind'.
adoConnection open.
adoCommand setActiveConnection: adoConnection.

adoResultSet := adoCommand execute.
```

This gives the error 
`HRESULT Error 0x80040E57: Unrecognised HRESULT - 16r80040E57 (FACILITY_ITF)`. 
Testing in D7.0 gives the more meaningful error 
`HRESULT Error: [Microsoft][ODBC Microsoft Access Driver]Invalid string or buffer length (FACILITY_ITF)`
As an aside, the more meaningful error message can be generated in D7.1 by manually invoking `COMInterface>>hresultError:` in the debugger - possibly this could be (re)added to `ExternalStructure>>invalidCall`?

The issue looks to be related to the use of a String parameter since a similar query using an Integer works ok:

```
adoCommand := ADODB_Command new.
adoCommand
	commandText: 'SELECT OrderID, OrderDate, RequiredDate, ShippedDate FROM Orders WHERE OrderID = ? ORDER BY OrderID';
	commandType: ADODBConstants.adCmdText;
	prepared: true.

param := adoCommand createParameter: 'OrdID' type: ADODBConstants.adInteger direction: ADODBConstants.adParamInput size: 0 value: 100000.
adoCommand parameters add: param.

adoConnection := ADODB_Connection new.
adoConnection  connectionString: 'Northwind'.
adoConnection open.
adoCommand setActiveConnection: adoConnection.

adoResultSet := adoCommand execute.
```

Unloading the ADODB package and regenerating the classes using the COM Component Wizard and Microsoft ActiveX Data Objects 6.1 Library fixes the issue, at the cost of losing the manual enhancements to the auto-generated classes (this necessitates changing `add:` to `append:` in the example). 

As a further aside, an error occurs during the class generation. This can be worked around by changing 
`argSizes ifNil: [argSizes := ByteArray newFixed: count*4].`
...to
`argSizes := ByteArray newFixed: count*4.`
...in `COMInterface class>>calcArgSizes` (the same as in D7.0). I'll raise this as a separate issue.

**Comment by blairmcg** [comment]
> As an aside, the more meaningful error message can be generated in D7.1 by manually invoking `COMInterface>>hresultError:` in the debugger - possibly this could be (re)added to `ExternalStructure>>invalidCall`?

That's an unintended consequent of 9ffb339942f86cc8a37b060dac0dc0e581f7d51e, and should definitely be restored to work with the way the primitive failure codes are returned now.

**Comment by blairmcg** [comment]
It should be possible to regenerate the wrappers without discarding the hand written content. I haven't tried that yet, however.

I did note that the query works once set up if the string parameter value is passed to the execute call:
```
...
adoResultSet := adoCommand execute: 'ALFKI' options: -1
```

**Comment by blairmcg** [comment]
I've regenerated it. If I use the same wizard options as were originally used, there is very little material difference. Aside from comments, the changes are either new versions of the interfaces (and there aren't even many of those) and the settings for some default parameters. It is the last of these that I think fixes the bug, but I didn't bother to investigate deeply since it now works.
