### ISSUE TITLE
Crash on startup "Fail to open image file C:\windows\system32\DPRO.img7"

### ISSUE THREAD

**Issue by bunglegrind** [dolphinsmalltalk/Dolphin#976]
Dear all,
i've just installed Dolphin 7.1.13 via Dolphin7Setup.exe on my windows 7 64 bit. 

But when I launch the software, the aforementioned error message appears.

The documentation on https://www.object-arts.com/gettingstarted.html _is not updated_ and it doesn't refer to the installer (btw, website certification has expired). 

Can you provide some hints in order to correctly start the software?

Thanks a lot

**Comment by brickviking** [comment]
Normally, an image is supposed to get copied to
C:\Users\<youruser>\Documents\Dolphin Smalltalk 7\DPRO.img7 as far as I
know, and the main binary and libs are supposed to be copied into
c:\Program Files\Dolphin Smalltalk 7\. I'm guessing something may have gone
wrong with the installer. Check the two locations to see what's there
currently.

Cheers, Brickviking

**Comment by blairmcg** [comment]
You may need to install the [VC++ runtime distribution](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads), specifically https://aka.ms/vs/16/release/vc_redist.x86.exe

I don't know if it still runs on Windows 7, however, as that went out of support almost 6 months ago now.

**Comment by bunglegrind** [comment]
> 
> Normally, an image is supposed to get copied to C:\Users\<youruser>\Documents\Dolphin Smalltalk 7\DPRO.img7 as far as I know, and the main binary and libs are supposed to be copied into c:\Program Files\Dolphin Smalltalk 7\. I'm guessing something may have gone wrong with the installer. Check the two locations to see what's there currently. Cheers, Brickviking
> […](#)
 Yep, the files are in the correct locations. The problem is that the Dolphin Smalltalk is looking for the image in a different path, \windows\system32\ and I don't want put the image there. 

Maybe a command line switch or a configuration setting?

**Comment by blairmcg** [comment]
Quite honestly nobody is maintaining the installer, and I don't want to. If nobody steps forward to do so within the next week or two, I'm just going to remove it. It's better to follow the instructions in the readme to bootstrap things yourself.

**Comment by bunglegrind** [comment]
oh, I see.

Anyway, I succeed in installing Dolphin following the readme and the "getting started" section aforementioned: you should update the website documentation (or delete it), even in the case of the "bootstrap" procedure is not updated.

Cheers

**Comment by brickviking** [comment]
Seems strange, as the last installer I ran, put things in the "right" places. I didn't check that out with this release, to be fair.
I get the initial licence agreement, then get prompted for the Destination Location, which appears to be correct (C:\Program Files\Dolphin Smalltalk 7), then get prompted to create a desktop shortcut. After that point, it croaks at the following stage at the "Extracting Files..." dialog (C:\users\viking\My Documents\Dolphin Smalltalk 7\DPRO.chg):

` "Select action:`
`C:\users\viking\My Documents\Dolphin Smalltalk 7\DPRO.chg`
` `
`An error occurred while trying to create a file in the destination directory: Setup was unable to create the directory "C:\users\viking\My Documents". Error 183: File already exists.``

No other buttons appear on the dialog, so I need to check this out under Vista, not just wine.

As for the installer, I'll take a look at it and see what I can do with it. I seem to recognise it from somewhere.

**Comment by bunglegrind** [comment]
>  I then get the "Completing the Dolphin Smalltalk Setup wizard: Launch Dolphin Smalltalk 7" box (paraphrasing here) and a Finish button. Dolphin 7 then starts up with the correct image.

Yes, it works...but then try to open again Dolphin using the desktop or the start menu icon, and the error message will appear.

But I think I've undestood the issue: it's related to the working directory/"start in" data field in the shortcut. 

When you start Dolphin, it looks for the img7 file only in the working directory which is set in one of the shortcut parameters ("start in" field). The issue arise when you have two or more users - my case actually. The working directory in the shortcuts is set to the admin Documents folder (because he has installed the software), but of course, my user cannot access to the admin documents folder and then - I don't know why - Dolphin fallbacks to system32. In fact, I have changed "starts in" to my documents folder, and Dolphin started correctly. 

A more appropriate behaviour IMHO should allow a more elaborate fallback procedure when the image is not found, or at least when creating the shortcuts, set the working directory to "%userprofile%\documents\Dolphin Smalltalk 7", which is relative to the current user.

**Comment by brickviking** [comment]
I believe (and this is only through behaviour I've observed over the years) that system32 is the fallback location when I do not specify a location explicitly. It's either that, or the Desktop directory of the user where I click the icon to start the program. I can't say what happens in any other case, only in what I've observed. I may be incorrect and I've only got Vista and Linux to go on.
